'use client';
import { UNIVERSE_METRICS, CHANGE_THRESHOLDS } from '../../utils/marketFundamentals.js';
import type { Breadth, FundamentalDiagnostics } from './marketUniverseTypes';
import s from './factorUniverse.module.css';

const value = (n:number|null|undefined) => typeof n==='number' ? n.toFixed(2) : '—';
const signed = (n:number|null|undefined) => typeof n==='number' ? `${n>0?'+':''}${n.toFixed(2)}` : '—';
const pct = (n:number|null|undefined) => typeof n==='number' ? `${n.toFixed(1)}%` : '—';
const range = (d:{earliest:string|null;latest:string|null}) => d.earliest ? d.earliest===d.latest ? d.earliest : `${d.earliest} to ${d.latest}` : 'Unavailable';

export default function MarketFundamentalDiagnostics({diagnostics,metric,onMetric,onThreshold,onScreen,groups,onGroup}:{
  diagnostics:FundamentalDiagnostics;metric:string;onMetric:(key:string)=>void;onThreshold:(n:number)=>void;
  onScreen:(screen:string,metric?:string)=>void;groups:{id:string;label:string;companies:number;breadth:Breadth[]}[];onGroup:(id:string)=>void;
}) {
  const m=diagnostics.breadth.find(x=>x.key===metric)||diagnostics.breadth[0],t=diagnostics.threshold,cash=diagnostics.cash_confirmation;
  const neutral=t ? `Within ±${t}` : 'Unchanged';
  const labels=[['higher','Faster growth'],['neutral',t?'Within band':'Unchanged growth'],['lower','Slower growth']];
  return <>
    <section className={s.panel} aria-labelledby="absolute-diagnostics-heading">
      <div className={s.sectionHeading}><div><h2 id="absolute-diagnostics-heading">Breadth, magnitude and dispersion</h2><p>Three separate measurements of the same filing comparisons. No peer rankings are averaged into a market score.</p></div><label>Financial measure<select value={metric} onChange={e=>onMetric(e.target.value)}>{UNIVERSE_METRICS.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label></div>
      <p>{m.meaning}</p>
      <div className={s.thresholdControl}><label>Direction threshold<select value={t} onChange={e=>onThreshold(Number(e.target.value))}>{CHANGE_THRESHOLDS.map(n=><option key={n} value={n}>{n===0?'All measured changes':`Outside ±${n} percentage points`}</option>)}</select></label><p>Test whether small changes drive breadth. Values inside the band stay in the denominator. Typical changes and dispersion always use the full paired sample.</p></div>
      <div className={s.diagnosticCards}>
        <article><h3>Breadth <span>How widespread?</span></h3><strong>{pct(m.higher_pct)} <small>higher</small></strong><p>{m.higher} higher · {m.lower} lower · {m.unchanged} {t?'inside band':'unchanged'} / {m.eligible} eligible</p><div className={s.breadthBar} role="img" aria-label={`${m.higher} higher, ${m.lower} lower and ${m.unchanged} neutral`}><span style={{width:`${m.higher_pct||0}%`}}/><i style={{width:`${m.lower_pct||0}%`}}/></div><p>Net direction balance <b>{signed(m.balance_pct)} percentage points</b></p><p className={s.caption}>Higher share minus lower share, from −100 to +100. Zero means balanced directions; it does not mean no change.</p><button className={s.textButton} onClick={()=>onScreen('direction:higher',m.key)}>Inspect increases</button></article>
        <article><h3>Magnitude <span>By how much?</span></h3><strong>{signed(m.change.median)} <small>percentage points</small></strong><p>Median change across the same {m.eligible} paired issuers.</p><dl><div><dt>Middle 50% of changes</dt><dd>{value(m.change.q25)} to {value(m.change.q75)}</dd></div><div><dt>Prior / current median level</dt><dd>{value(m.prior.median)}% / {value(m.current.median)}%</dd></div></dl><p className={s.caption}>Median issuer change is calculated directly. Subtracting the two cross-sectional medians can give a different result.</p></article>
        <article><h3>Dispersion <span>How uneven?</span></h3><strong>{signed(m.paired_iqr_change)} <small>percentage points</small></strong><p>{m.paired_iqr_change===null?'Paired spread is unavailable.':Math.abs(m.paired_iqr_change)<.005?'The middle-50% range is approximately unchanged.':m.paired_iqr_change>0?'The middle-50% range of outcomes widened.':'The middle-50% range of outcomes narrowed.'}</p><dl><div><dt>Prior / current range (IQR)</dt><dd>{value(m.prior.iqr)} / {value(m.current.iqr)}</dd></div><div><dt>Paired issuers</dt><dd>{m.eligible}</dd></div></dl><p className={s.caption}>{m.key==='revenueGrowth'?'Spread is measured in revenue-growth rates; magnitude above measures their acceleration.':'Spread describes differences in ratio levels across companies.'} Wider does not automatically mean better or worse.</p></article>
      </div>
      <div className={s.periodEvidence}><p><b>Comparable sample:</b> {m.eligible} of {m.population_count} eligible issuer types; {m.missing} missing comparisons. {m.population==='operating'?'Financial and property/investment issuers are excluded.':'All issuer types may qualify.'}</p><p><b>Current fiscal ends:</b> {range(m.fiscal_ends)} · <b>Prior fiscal ends:</b> {range(m.prior_fiscal_ends)}</p><p><b>Filing dates:</b> {range(m.filing_dates)}. Comparisons end about one year apart for each issuer; reporting calendars vary.</p></div>
      <details><summary>Compare all six measures and inspect the formulas</summary><div className={s.tableWrap}><table><caption>Direction band: {t===0?'all measured changes':`±${t} percentage points`} · changes and spreads in percentage points</caption><thead><tr><th>Measure</th><th>Comparable pairs</th><th>Higher / lower / neutral</th><th>Net balance</th><th>Median change</th><th>Change in IQR</th></tr></thead><tbody>{diagnostics.breadth.map(x=><tr key={x.key}><th><button className={s.textButton} onClick={()=>onMetric(x.key)}>{x.short}</button></th><td>{x.eligible} / {x.population_count}</td><td>{x.higher} / {x.lower} / {x.unchanged}</td><td>{signed(x.balance_pct)}</td><td>{signed(x.change.median)}</td><td>{signed(x.paired_iqr_change)}</td></tr>)}</tbody></table></div><p>Breadth = higher count / paired count. Net balance = 100 × (higher count − lower count) / paired count. Magnitude = median(current − prior). IQR = 75th percentile − 25th percentile; change in spread = current IQR − prior IQR on the same issuers. Thresholds are sensitivity settings, not significance tests or universal economic cutoffs.</p></details>
    </section>

    <section className={s.panel} aria-labelledby="cash-confirmation-heading"><h2 id="cash-confirmation-heading">Does faster growth have cash-margin support?</h2>{cash.eligible>0?<><p>Revenue-growth acceleration and free cash flow margin changes, compared across the <b>same {cash.eligible} operating businesses</b>.</p>
      <p>{cash.growth_higher} show faster growth and {cash.cash_higher} show a higher cash margin. {cash.growth_higher>0?<>Of the {cash.growth_higher} faster-growth businesses, {cash.both_higher} also show a higher cash margin ({pct(cash.confirmation_pct)}).</>:'No business exceeds the selected growth band, so conditional cash confirmation is unavailable.'}</p>
      <p>On this matched sample, growth acceleration is present at {pct(cash.growth_higher_pct)} and cash-margin increases at {pct(cash.cash_higher_pct)}. The difference is {signed(cash.higher_share_gap)} percentage points (growth share minus cash-margin share).</p><div className={s.tableWrap}><table className={s.confirmationTable}><caption>Each cell counts issuers with both comparisons. Select a count to inspect those businesses.</caption><thead><tr><th>Revenue-growth change</th><th>Higher cash margin</th><th>{neutral} cash margin</th><th>Lower cash margin</th></tr></thead><tbody>{labels.map(([growth,label])=><tr key={growth}><th>{label}</th>{['higher','neutral','lower'].map(c=>{const cell=cash.cells.find(x=>x.growth===growth&&x.cash===c)!;return <td key={c}><button className={s.matrixButton} disabled={!cell.count} aria-label={`Inspect ${cell.count} issuers: ${label}, ${c==='neutral'?'neutral':c} cash margin`} onClick={()=>onScreen(`cash:${growth}:${c}`,'freeCashFlowMargin')}><b>{cell.count}</b><small>{pct(cell.pct)} of matched sample</small></button></td>;})}</tr>)}</tbody></table></div>
      <div className={s.periodEvidence}><p>{cash.eligible} of {cash.population} operating issuers have both comparisons; {cash.missing} are unavailable. Direction band: {t===0?'all measured changes':`±${t} percentage points`}.</p><p>Current fiscal ends {range(cash.fiscal_ends)} · prior fiscal ends {range(cash.prior_fiscal_ends)} · filings {range(cash.filing_dates)}.</p></div><p>A lower cash margin can reflect capital investment or working-capital needs. It does not necessarily mean falling cash flow in dollars. Faster growth can still describe a smaller revenue decline.</p></>:<p className={s.empty}>No operating businesses in this scope have both comparable growth and cash-margin changes. Financial and property/investment issuers are excluded from this comparison.</p>}
    </section>

    <section className={s.panel}><h2>Where is the change concentrated?</h2><p>{m.label} across primary research groups. Each issuer belongs to one group; these are curated research themes.</p><div className={s.tableWrap}><table><thead><tr><th>Research group</th><th>Paired / eligible types</th><th>Higher share</th><th>Net balance</th><th>Median change</th><th>Change in IQR</th></tr></thead><tbody>{groups.map(g=>{const x=g.breadth.find(b=>b.key===m.key)!;return <tr key={g.id}><th><button className={s.textButton} onClick={()=>onGroup(g.id)}>{g.label}</button></th><td>{x.eligible} / {x.population_count}</td><td>{pct(x.higher_pct)}</td><td>{signed(x.balance_pct)}</td><td>{signed(x.change.median)}</td><td>{signed(x.paired_iqr_change)}</td></tr>;})}</tbody></table></div>
      <details><summary>Quantify dispersion within and between groups in this scope</summary><p>This additional decomposition uses variance, which is sensitive to extreme values. It complements the middle-50% range above. Group membership and issuer weights remain identical across both periods.</p><div className={s.tableWrap}><table><caption>{m.variance.eligible} paired issuers · {m.variance.groups} groups · variance in squared percentage points</caption><thead><tr><th>Variance component</th><th>Prior</th><th>Current</th><th>Change</th></tr></thead><tbody>{[['within','Within groups'],['between','Between group averages'],['total','Total']].map(([key,label])=>{const k=key as 'within'|'between'|'total';return <tr key={key}><th>{label}</th><td>{value(m.variance.prior[k])}</td><td>{value(m.variance.current[k])}</td><td>{signed(m.variance.change[k])}</td></tr>;})}</tbody></table></div><p>Within-group share: {pct(m.variance.prior.within_share===null?null:m.variance.prior.within_share*100)} prior; {pct(m.variance.current.within_share===null?null:m.variance.current.within_share*100)} current. A changing share alone does not establish a change in the absolute variance component.</p><p>Total variance = within-group variance + between-group variance. Within = Σ(group count / total count) × group population variance. Between = Σ(group count / total count) × (group mean − universe mean)². IQRs and standard deviations do not add this way. {m.variance.singleton_groups} groups have one eligible issuer and contribute no within-group variance.</p></details>
    </section>
  </>;
}
