'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, ChevronLeft, ChevronRight, Search, X } from 'lucide-react';
import { isMarketSectorCompaniesPage } from '../../utils/marketResearchValidation.js';
import { formatMarket } from '../../utils/marketResearch.js';
import type { Basis, MarketSector } from './marketTypes';
import s from './marketSectorCompanies.module.css';

export type CompanyViewPatch = { companyMetric?: string; companyDirection?: 'asc' | 'desc'; companyQuery?: string; companyPage?: number };
type Metric = { key: string; label: string; group: string; unit: 'pct' | 'ratio' | 'usd' | 'text'; note: string };
export const COMPANY_METRICS: Metric[] = [
  { key: 'revenueGrowth', label: 'Revenue growth', group: 'Growth', unit: 'pct', note: 'Revenue change from the comparable prior-year period.' },
  { key: 'netMargin', label: 'Net margin', group: 'Profitability', unit: 'pct', note: 'Net income as a share of revenue.' },
  { key: 'operatingMargin', label: 'Operating margin', group: 'Profitability', unit: 'pct', note: 'Operating income as a share of revenue.' },
  { key: 'cashFlowMargin', label: 'Operating cash flow / revenue', group: 'Cash generation', unit: 'pct', note: 'Cash generated by operations as a share of revenue.' },
  { key: 'freeCashFlowMargin', label: 'Free cash flow / revenue', group: 'Cash generation', unit: 'pct', note: 'Operating cash flow less PP&E purchases, divided by revenue.' },
  { key: 'debtToAssets', label: 'Credit · Debt / assets', group: 'Risk', unit: 'pct', note: 'Reported borrowing relative to total assets. Smaller values indicate less balance-sheet borrowing.' },
  { key: 'liabilitiesToAssets', label: 'Credit · Liabilities / assets', group: 'Risk', unit: 'pct', note: 'All reported liabilities relative to assets; this is broader than debt.' },
  { key: 'currentRatio', label: 'Liquidity · Current ratio', group: 'Risk', unit: 'ratio', note: 'Current assets divided by current liabilities. Some financial companies do not report a classified balance sheet.' },
  { key: 'cashToAssets', label: 'Liquidity · Cash / assets', group: 'Risk', unit: 'pct', note: 'Reported cash and cash equivalents as a share of total assets.' },
  { key: 'interestCoverage', label: 'Coverage · Interest coverage', group: 'Risk', unit: 'ratio', note: 'Operating income divided by interest expense, where compatible inputs are available.' },
  { key: 'equityToAssets', label: 'Equity · Book equity / assets', group: 'Risk', unit: 'pct', note: 'Reported stockholders’ equity relative to total assets.' },
  { key: 'totalAssets', label: 'Total assets', group: 'Company & size', unit: 'usd', note: 'Total assets at the reported period end.' },
  { key: 'revenue', label: 'Revenue', group: 'Company & size', unit: 'usd', note: 'Reported revenue for the selected basis. Revenue definitions can vary by business model.' },
  { key: 'ticker', label: 'Ticker', group: 'Company & size', unit: 'text', note: 'Alphabetical company symbols. Each SEC issuer appears once.' },
];
const GROUPS = ['Growth', 'Profitability', 'Cash generation', 'Risk', 'Company & size'];
type CompanyRow = { ticker: string; name: string; cik: string; sic: string; sectorId: string; revenueBasis?: string; report: { end: string | null; filed: string | null; form: string | null; accession: string | null } | null; metrics: Record<string, number | null> };
type CompanyPage = { version: 'market-sector-companies-v1'; generatedAt: string; sector: string; basis: Basis; query: string; sort: string; direction: 'asc' | 'desc'; page: number; pageSize: number; total: number; sectorTotal: number; availableCount: number; range: { min: number; max: number; median: number } | null; companies: CompanyRow[] };
type Props = { sector: MarketSector; basis: Basis; generatedAt: string; metric: string; direction: 'asc' | 'desc'; query: string; page: number; onChange: (patch: CompanyViewPatch) => void };
const pages = new Map<string, { at: number; value: CompanyPage }>();
const CACHE_MS = 5 * 60 * 1000;
const normalizedQuery = (value: string) => value.trim().replace(/\s+/g, ' ').toLowerCase();
const metricValue = (value: number | null | undefined, unit: Metric['unit']) => value == null ? '—' : unit === 'ratio' ? `${value.toFixed(2)}×` : formatMarket(value, unit, 1);

export function companyFilingUrl(company: CompanyRow) {
  const accession = company.report?.accession;
  return /^\d{1,10}$/.test(company.cik) && accession && /^\d{10}-\d{2}-\d{6}$/.test(accession)
    ? `https://www.sec.gov/Archives/edgar/data/${Number(company.cik)}/${accession.replaceAll('-', '')}/${accession}-index.html` : null;
}

export default function MarketSectorCompanies({ sector, basis, generatedAt, metric, direction, query, page, onChange }: Props) {
  const selectedMetric = COMPANY_METRICS.find(row => row.key === metric) || COMPANY_METRICS[0];
  const [draft, setDraft] = useState(query);
  const [result, setResult] = useState<{ key: string; value: CompanyPage } | null>(null);
  const [error, setError] = useState<{ key: string; message: string } | null>(null);
  const [attempt, setAttempt] = useState(0);
  const changeRef = useRef(onChange);
  useEffect(() => { changeRef.current = onChange; }, [onChange]);
  useEffect(() => { setDraft(query); }, [query]);
  useEffect(() => {
    if (draft === query) return;
    const timer = setTimeout(() => changeRef.current({ companyQuery: draft, companyPage: 1 }), 250);
    return () => clearTimeout(timer);
  }, [draft, query]);
  const search = normalizedQuery(query);
  const path = `/api/market-sector-companies?${new URLSearchParams({ sector: sector.id, basis, query: search, sort: selectedMetric.key, direction, page: String(page) })}`;
  const cacheKey = `${generatedAt}:${path}`;

  useEffect(() => {
    const cached = pages.get(cacheKey);
    if (cached && Date.now() - cached.at < CACHE_MS) { setResult({ key: cacheKey, value: cached.value }); setError(null); return; }
    let current = true;
    let timedOut = false;
    const controller = new AbortController();
    const timeout = setTimeout(() => { timedOut = true; controller.abort(); }, 15_000);
    setError(null);
    void (async () => {
      try {
        const response = await fetch(path, { signal: controller.signal, ...(attempt > 0 ? { cache: 'no-cache' as const } : {}) });
        const value = await response.json();
        if (!response.ok || !isMarketSectorCompaniesPage(value, { sector: sector.id, basis, query: search, sort: selectedMetric.key, direction, page })) throw new Error('Company data could not be verified. Please retry.');
        if (!current) return;
        pages.delete(cacheKey); pages.set(cacheKey, { at: Date.now(), value });
        while (pages.size > 12) pages.delete(pages.keys().next().value!);
        setResult({ key: cacheKey, value });
      } catch (reason) {
        if (current) setError({ key: cacheKey, message: timedOut ? 'Company data is taking longer than expected. Please retry.' : reason instanceof Error ? reason.message : 'Could not load sector companies.' });
      } finally { clearTimeout(timeout); }
    })();
    return () => { current = false; clearTimeout(timeout); controller.abort(); };
  }, [cacheKey, path, sector.id, basis, search, selectedMetric.key, direction, page, attempt]);

  const data = result?.key === cacheKey ? result.value : null;
  const message = error?.key === cacheKey ? error.message : null;
  const pendingSearch = normalizedQuery(draft) !== search;
  const busy = !data && !message || pendingSearch;
  const numeric = selectedMetric.unit !== 'text';
  const range = data?.range;
  const span = range ? Math.max(Math.abs(range.min), Math.abs(range.max), Number.EPSILON) : 1;
  const pageCount = data ? Math.max(1, Math.ceil(data.total / data.pageSize)) : 1;
  const first = data?.total ? (data.page - 1) * data.pageSize + 1 : 0;
  const last = data ? Math.min(data.page * data.pageSize, data.total) : 0;
  const chooseMetric = (key: string) => onChange({ companyMetric: key, companyPage: 1, ...(key === 'ticker' ? { companyDirection: 'asc' } : {}) });

  return <section id="sector-companies" className={s.explorer} aria-labelledby="sector-companies-title">
    <div className={s.heading}>
      <div><span className={s.eyebrow}>Explore the companies</span><h2 id="sector-companies-title">Inside {sector.label}</h2><p className={s.description}>Find the companies behind the sector. Compare their reported fundamentals.</p></div>
      <div className={s.scope}><strong>{(data?.sectorTotal ?? sector.count).toLocaleString()}</strong><span>companies · {basis === 'ttm' ? 'Latest TTM' : 'Latest annual'}</span></div>
    </div>
    <div className={s.categories} role="group" aria-label="Company metric category">{GROUPS.map(group => <button key={group} type="button" aria-pressed={selectedMetric.group === group} onClick={() => chooseMetric(COMPANY_METRICS.find(row => row.group === group)!.key)}>{group}</button>)}</div>
    <div className={s.controls}>
      <label className={s.search}><Search size={16} aria-hidden="true" /><span className={s.srOnly}>Search companies in {sector.label}</span><input type="search" value={draft} maxLength={100} placeholder="Find a name or ticker in this sector" onChange={event => setDraft(event.target.value)} />{draft && <button type="button" aria-label="Clear company search" onClick={() => { setDraft(''); onChange({ companyQuery: '', companyPage: 1 }); }}><X size={14} /></button>}</label>
      <label className={s.metricSelect}><span>Sort companies by</span><select value={selectedMetric.key} onChange={event => chooseMetric(event.target.value)}>{GROUPS.map(group => <optgroup key={group} label={group}>{COMPANY_METRICS.filter(row => row.group === group).map(row => <option key={row.key} value={row.key}>{row.label}</option>)}</optgroup>)}</select></label>
      <button className={s.direction} type="button" onClick={() => onChange({ companyDirection: direction === 'asc' ? 'desc' : 'asc', companyPage: 1 })} aria-label={`Sort ${direction === 'desc' ? 'lowest' : 'highest'} first`}>{direction === 'desc' ? <ArrowDown size={15} /> : <ArrowUp size={15} />}<span>{numeric ? direction === 'desc' ? 'Highest first' : 'Lowest first' : direction === 'asc' ? 'A to Z' : 'Z to A'}</span></button>
    </div>
    <p className={s.metricNote}>{selectedMetric.note}</p>
    <div className={s.resultsHeading} aria-live="polite">
      <span>{busy ? 'Loading companies…' : data ? `${first.toLocaleString()}–${last.toLocaleString()} of ${data.total.toLocaleString()}${search ? ' matching companies' : ' companies'}` : 'Company coverage'}</span>
      {data && numeric && <span><b>{data.availableCount.toLocaleString()}</b> with data{range && <> · {search ? 'Match' : 'Sector'} median <b>{metricValue(range.median, selectedMetric.unit)}</b></>}{data.total > data.availableCount && <> · {data.total - data.availableCount} unavailable</>}</span>}
    </div>
    {message ? <div className={s.empty} role="alert"><p>{message}</p><button type="button" onClick={() => { pages.delete(cacheKey); setAttempt(value => value + 1); }}>Retry companies</button></div> : !data ? <div className={s.loading} role="status">Loading the sector’s company snapshot…</div> : !data.total ? <div className={s.empty}><h3>No companies match “{query}”</h3><p>Try a company name or ticker in {sector.label}.</p><button type="button" onClick={() => { setDraft(''); onChange({ companyQuery: '', companyPage: 1 }); }}>Show all sector companies</button></div> : <>
      {numeric && data.availableCount === 0 && <p className={s.coverageNote}>This snapshot has no compatible {selectedMetric.label.toLowerCase()} values for these companies. Company details remain available below.</p>}
      <div className={s.tableScroll} tabIndex={0} aria-label={`${sector.label} companies, sorted by ${selectedMetric.label.toLowerCase()}`} aria-busy={busy}>
        <table className={s.table}><caption className={s.srOnly}>{sector.label} companies. Sorted by {selectedMetric.label.toLowerCase()}, {direction === 'desc' ? 'highest' : 'lowest'} first. Missing values appear last.</caption>
          <thead><tr><th scope="col">Company</th><th scope="col" aria-sort={direction === 'desc' ? 'descending' : 'ascending'}>{selectedMetric.label}{numeric && <small>Bars share a scale across all {search ? 'matches' : 'sector companies'}</small>}</th><th scope="col">Period end</th><th scope="col"><span className={s.srOnly}>Inspect company</span></th></tr></thead>
          <tbody>{data.companies.map(company => {
            const value = company.metrics[selectedMetric.key] ?? null;
            const width = value == null ? 0 : Math.min(50, Math.abs(value) / span * 50);
            const filingUrl = companyFilingUrl(company);
            const href = `/analysis/${encodeURIComponent(company.ticker)}?basis=${basis === 'annual' ? 'annual' : 'ttm'}`;
            return <tr key={company.cik}>
              <th scope="row"><Link prefetch={false} href={href} className={s.company}><strong>{company.ticker}</strong><span>{company.name}</span></Link>{company.revenueBasis && company.revenueBasis !== 'Reported total revenue' && ['revenue', 'revenueGrowth', 'netMargin', 'operatingMargin', 'cashFlowMargin', 'freeCashFlowMargin'].includes(selectedMetric.key) && <small className={s.revenueBasis}>{company.revenueBasis}</small>}</th>
              <td><div className={s.metricCell}>{numeric && <span className={s.barTrack} aria-hidden="true"><i className={value != null && value < 0 ? s.negativeBar : s.positiveBar} style={{ width: `${width}%`, left: `${value != null && value < 0 ? 50 - width : 50}%` }} /></span>}<strong className={value == null && numeric ? s.missing : undefined}>{numeric ? metricValue(value, selectedMetric.unit) : company.ticker}</strong></div></td>
              <td className={s.period}>{company.report?.end ? filingUrl ? <a href={filingUrl} target="_blank" rel="noopener noreferrer" aria-label={`${company.ticker}: period ending ${company.report.end}, open latest source filing`}>{company.report.end}<ArrowUpRight size={11} /></a> : <span>{company.report.end}</span> : <span>Unavailable</span>}{company.report?.filed && <small>Filed {company.report.filed}</small>}</td>
              <td><div className={s.links}><Link prefetch={false} href={href} aria-label={`Analyze ${company.ticker}`}>Analysis<ArrowUpRight size={12} /></Link><Link prefetch={false} href={`/risk?ticker=${encodeURIComponent(company.ticker)}`} aria-label={`Inspect ${company.ticker} risk`}>Risk<ArrowUpRight size={12} /></Link></div></td>
            </tr>;
          })}</tbody>
        </table>
      </div>
      <div className={s.pagination}><span>Page {data.page} of {pageCount}</span><button type="button" disabled={data.page <= 1 || pendingSearch} onClick={() => onChange({ companyPage: data.page - 1 })} aria-label="Previous company page"><ChevronLeft size={15} />Previous</button><button type="button" disabled={data.page >= pageCount || pendingSearch} onClick={() => onChange({ companyPage: data.page + 1 })} aria-label="Next company page">Next<ChevronRight size={15} /></button></div>
    </>}
    <p className={s.footnote}>Missing values stay unavailable and sort last. Balance-sheet measures use period-end balances; TTM flow measures span twelve months. Periods and accounting definitions vary. {selectedMetric.group === 'Risk' && 'Risk ratios describe reported financials, not credit ratings. '}{sector.id === 'sector-financials' && 'Bank and insurer business models can limit ratio comparability. '}Colors indicate the sign of a value, not its quality.</p>
    {data && data.generatedAt !== generatedAt && <p className={s.footnote}>Company snapshot: {data.generatedAt.slice(0, 16).replace('T', ' ')} UTC.</p>}
  </section>;
}
