export type Distribution = {count:number;median:number|null;q25:number|null;q75:number|null;iqr:number|null;minimum:number|null;maximum:number|null};
export type Breadth = {key:string;label:string;short:string;population:string;meaning:string;threshold:number;balance_pct:number|null;eligible_tickers:string[];prior_fiscal_ends:{earliest:string|null;latest:string|null};variance:GroupVariance;population_count:number;eligible:number;missing:number;higher:number;lower:number;unchanged:number;higher_pct:number|null;lower_pct:number|null;change:Distribution;current:Distribution;prior:Distribution;paired_iqr_change:number|null;filing_dates:{earliest:string|null;latest:string|null};fiscal_ends:{earliest:string|null;latest:string|null}};
export type UniverseRow = {ticker:string;cik:string;name:string;group:string;cohorts:string[];financial:boolean;metrics:Record<string,{current:number|null;prior:number|null;change:number|null;unavailable_reason:string|null}>;exposure:{beta:number;beta_interval:[number,number]|null;downside_beta:number|null;sector_beta:number|null;r_squared:number|null;residual_volatility:number|null;observations:number;through:string;start:string}|null;sector_proxy:string|null;event:{return:number;response_z:number|null;through:string;first_session:string;timing:string}|null;filed:string|null;fiscal_end:string|null;prior_fiscal_end:string|null;accession:string|null;source:string|null};
export type CoMovement = {available:boolean;reason?:string;issuers:number;population:number;coverage:number;sessions:number;pairs:number;eligible_tickers:string[];prior_start:string|null;prior_end:string|null;current_start:string|null;current_end:string|null;prior:{mean:number;pairs:number}|null;current:{mean:number;pairs:number}|null;change:number|null;rolling:{through:string;mean:number;pairs:number}[]};
export type Scope = {id:string;label:string;companies:number;breadth:Breadth[];cash_confirmation:CashConfirmation;simultaneous_weakening:{count:number;eligible:number;missing:number;pct:number|null;tickers:string[]};exposure:{eligible:number;coverage:number;distributions:Record<string,Distribution>};map:{eligible:number;opposite_signs:number};associations:{metric:string;label:string;observations:number;rho:number|null;filing_dates:{earliest:string|null;latest:string|null};eligible_tickers:string[]}[];co_movement:CoMovement;brief:string[]};
export type UniverseSnapshot = {schema_version:string;methodology_version:string;generated_at:string;sec_snapshot_at:string;sec_stale:boolean;price_through:string|null;basis:'ttm'|'annual';status:string;cache_status?:string;price_status?:string;refresh_warning?:string;history_note?:string;universe:{requested:number;issuers:number;share_classes_excluded:number;grouping:string;coverage?:{membership_id:string;target_issuers:number;loaded_issuers:number;missing_issuers:number;source_securities:number;duplicate_share_classes:number;membership_checked_at:string;sec_checked_earliest:string;sec_checked_latest:string;sources:{fund:string;as_of:string;url:string;securities:number}[]}|null};scopes:Record<string,Scope>;rows:UniverseRow[];history:{observed_at:string;sec_snapshot_at:string;issuers:string[];breadth:{metric:string;higher:number;eligible:number;median_change:number|null}[]}[];limitations:string[];links:{methodology:string;schema:string;api:string}};

export type VariancePeriod = {total:number|null;within:number|null;between:number|null;within_share:number|null;between_share:number|null};
export type GroupVariance = {eligible:number;groups:number;singleton_groups:number;units:string;current:VariancePeriod;prior:VariancePeriod;change:{total:number|null;within:number|null;between:number|null}};
export type CashConfirmation = {threshold:number;population:number;eligible:number;missing:number;coverage:number;growth_higher:number;cash_higher:number;both_higher:number;growth_higher_pct:number|null;cash_higher_pct:number|null;higher_share_gap:number|null;confirmation_pct:number|null;cells:{growth:string;cash:string;count:number;pct:number|null;tickers:string[]}[];filing_dates:{earliest:string|null;latest:string|null};fiscal_ends:{earliest:string|null;latest:string|null};prior_fiscal_ends:{earliest:string|null;latest:string|null}};
export type FundamentalDiagnostics = {threshold:number;breadth:Breadth[];cash_confirmation:CashConfirmation;simultaneous_weakening:Scope['simultaneous_weakening']};
