'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowLeft, Download, ExternalLink, Loader2, RefreshCw } from 'lucide-react';
import { downloadText } from '../../utils/download.js';
import { UNIVERSE_VERSION, universeMarkdown, UNIVERSE_METRICS } from '../../utils/marketUniverse.js';
import type { MarketData, MarketView } from './marketTypes';
import type { UniverseSnapshot, UniverseRow, Breadth, CoMovement } from './marketUniverseTypes';
import s from './factorUniverse.module.css';
const CompanyLab=dynamic(()=>import('./MarketFactorLab'),{ssr:false,loading:()=> <p role="status">Loading company diagnostics…</p>});
const cache=new Map<string,{at:number;data:UniverseSnapshot}>();
const number=(n:number|null|undefined,d=2)=>typeof n==='number'&&Number.isFinite(n)?n.toFixed(d):'—';
const percent=(n:number|null|undefined)=>typeof n==='number'&&Number.isFinite(n)?`${n.toFixed(1)}%`:'—';
const decimalPercent=(n:number|null|undefined)=>typeof n==='number'?percent(n*100):'—';
const signed=(n:number|null|undefined)=>typeof n==='number'?`${n>0?'+':''}${n.toFixed(2)}`:'—';
const day=(value:string|null|undefined)=>value?.slice(0,10)||'Unavailable';

function BreadthCard({metric,onSelect}:{metric:Breadth;onSelect:()=>void}){
  return <article className={s.breadthCard}><h3>{metric.short}</h3><strong>{percent(metric.higher_pct)} <small>higher</small></strong><p>{metric.higher} of {metric.eligible} comparable issuers</p>
    <div className={s.breadthBar} role="img" aria-label={`${metric.higher} higher, ${metric.lower} lower, ${metric.unchanged} unchanged; ${metric.missing} unavailable`}><span style={{width:`${metric.higher_pct||0}%`}}/><i style={{width:`${metric.lower_pct||0}%`}}/></div>
    <div className={s.split}><span>{percent(metric.lower_pct)} lower</span><span>{metric.missing} unavailable</span></div>
    <p className={s.magnitude}>Typical change <b>{signed(metric.change.median)} percentage points</b></p>
    <details><summary>What this tells you</summary><p>{metric.meaning}</p><p>Higher/lower compares each issuer with its own comparable prior-year period. The median describes a typical change; it is not the difference between two market averages.</p><p>{metric.population==='operating'?'Excludes financial and property/investment issuers classified under SIC 6000–6799.':'All issuer types are eligible when both values are available.'}</p></details>
    <button className={s.textButton} onClick={onSelect}>Inspect the companies</button></article>;
}
function CoMovementChart({data}:{data:CoMovement}){
  const points=data.rolling.filter(p=>typeof p.mean==='number');
  if(!data.available)return <p className={s.empty}>{data.reason}</p>;
  const path=points.map((p,i)=>`${i?'L':'M'} ${35+i*510/Math.max(1,points.length-1)} ${150-p.mean*115}`).join(' ');
  return <><div className={s.pair}><div><span>Latest 63 sessions</span><strong>{number(data.current?.mean)}</strong></div><div><span>Previous 63 sessions</span><strong>{number(data.prior?.mean)}</strong></div></div>
    <p>Average company-pair correlation {Math.abs(data.change||0)<.0001?'was approximately unchanged; absolute change':data.change!>0?'increased':'decreased'} by {number(Math.abs(data.change||0))}. {Math.abs(data.change||0)<.0001?'':data.change!>0?'The same companies moved more closely together.':'The same companies moved less closely together.'}</p>
    <svg viewBox="0 0 580 285" className={s.lineChart} role="img" aria-label={`Rolling 63-session average pairwise correlation, ${data.prior?.mean.toFixed(2)} to ${data.current?.mean.toFixed(2)}`}><line x1="35" x2="545" y1="150" y2="150"/><text x="5" y="40">1</text><text x="5" y="154">0</text><text x="0" y="270">−1</text><path d={path}/></svg>
    <p className={s.caption}>{data.issuers} fixed issuers · {data.current?.pairs} valid pairs · {day(data.prior_start)}–{day(data.current_end)}. Windows advance seven sessions. The comparison uses adjacent 63-session periods; the intervening chart windows overlap.</p><details><summary>Interpretation and exact observations</summary><p>Correlation ranges from −1 to +1. It measures co-movement, not causation or a portfolio’s risk reduction. The same issuer set has complete returns on all 126 benchmark intervals; at least 8 issuers and 60% of this scope must qualify.</p><div className={s.tableWrap}><table><thead><tr><th>Window through</th><th>Average correlation</th><th>Pairs</th></tr></thead><tbody>{points.map(p=><tr key={p.through}><th>{p.through}</th><td>{number(p.mean,4)}</td><td>{p.pairs}</td></tr>)}</tbody></table></div></details></>;
}
function FilingMap({rows,metric,onCompany}:{rows:UniverseRow[];metric:string;onCompany:(ticker:string)=>void}){
  const data=rows.filter(r=>typeof r.metrics[metric]?.change==='number'&&typeof r.event?.response_z==='number'&&(!['operatingMargin','freeCashFlowMargin','cashToAssets'].includes(metric)||!r.financial));
  if(!data.length)return <p className={s.empty}>No companies in this scope have both a comparable filing change and a complete 20-session price response. Their available SEC results remain in the table below.</p>;
  const xmax=Math.max(1,...data.map(r=>Math.abs(r.metrics[metric].change!)))*1.08,ymax=Math.max(1,...data.map(r=>Math.abs(r.event!.response_z!)))*1.08;
  const label=UNIVERSE_METRICS.find(m=>m.key===metric)?.label||metric;
  const axisLabel=metric==='revenueGrowth'?label:`${label} change`;
  return <><svg viewBox="0 0 720 390" className={s.map} role="group" aria-label={`${data.length} companies: ${axisLabel} in percentage points on the horizontal axis, standardized post-filing response on the vertical axis.`}>
    <line x1="80" x2="670" y1="175" y2="175"/><line x1="375" x2="375" y1="25" y2="325"/>
    <text x="90" y="42">Lower filing measure / positive response</text><text x="425" y="42">Higher / positive</text><text x="90" y="315">Lower / negative</text><text x="425" y="315">Higher / negative</text>
    <text x="80" y="350">{signed(-xmax)}</text><text x="365" y="350">0</text><text x="640" y="350">{signed(xmax)}</text><text x="140" y="377">{axisLabel} · percentage points</text>
    <text x="5" y="24">+{number(ymax,1)}</text><text x="5" y="180">0</text><text x="5" y="325">−{number(ymax,1)}</text>
    {data.map(r=><circle key={r.ticker} cx={375+r.metrics[metric].change!/xmax*285} cy={175-r.event!.response_z!/ymax*145} r="5" role="button" tabIndex={0} aria-label={`Inspect ${r.ticker}: filing change ${signed(r.metrics[metric].change)} percentage points, response ${signed(r.event!.response_z)}`} onClick={()=>onCompany(r.ticker)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onCompany(r.ticker);}}}><title>{r.ticker}: change {signed(r.metrics[metric].change)}; response {signed(r.event!.response_z)}; filed {r.filed}</title></circle>)}
    </svg><p className={s.caption}>{data.length} of {rows.length} issuers plotted. Values are not clipped. Vertical axis: cumulative model-adjusted log return divided by the pre-event residual-noise scale over 20 sessions. Filing dates vary; this is a collection of issuer events.</p></>;
}
export default function MarketFactorUniverse({atlas,view,onView,onNotice}:{atlas:MarketData|null;view:MarketView;onView:(patch:Partial<MarketView>)=>void;onNotice:(message:string)=>void}){
  const [snapshot,setSnapshot]=useState<UniverseSnapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
  const [section,setSection]=useState('fundamentals'),[metric,setMetric]=useState('revenueGrowth'),[query,setQuery]=useState(''),[sort,setSort]=useState('change'),[screen,setScreen]=useState('all'),[page,setPage]=useState(0),[detail,setDetail]=useState<string|null>(null);
  const constituentRef=useRef<HTMLElement>(null),detailRef=useRef<HTMLElement>(null),rootRef=useRef<HTMLElement>(null);
  useEffect(()=>{
    const root=rootRef.current,header=document.querySelector('header');if(!root||!header)return;
    const measure=()=>root.style.setProperty('--header-clearance',`${header.getBoundingClientRect().height+20}px`);measure();const observer=new ResizeObserver(measure);observer.observe(header);return()=>observer.disconnect();
  },[]);
  useEffect(()=>{
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
    const basis=view.basis;let active=true;
    setLoading(true);setError('');
    const prior=cache.get(basis);
    if(prior&&Date.now()-prior.at<300000&&retry===0){setSnapshot(prior.data);setLoading(false);clearTimeout(timer);return()=>controller.abort();}
    fetch(`/api/v1/factor-universe?basis=${basis}`,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok||result.schema_version!==UNIVERSE_VERSION||!result.scopes?.all)throw new Error(result.error||'The universe snapshot is unavailable.');return result as UniverseSnapshot;}).then(result=>{if(!active)return;setSnapshot(result);if(result.status==='ready')cache.set(basis,{at:Date.now(),data:result});}).catch(err=>{if(active)setError(err.name==='AbortError'?'The snapshot request timed out. Please retry.':err.message);}).finally(()=>{clearTimeout(timer);if(active)setLoading(false);});
    return()=>{active=false;clearTimeout(timer);controller.abort();};
  },[view.basis,retry]);
  const current=snapshot?.basis===view.basis?snapshot:null;
  const scope=current?.scopes[view.cohort]||current?.scopes.all;
  const selected=useMemo(()=>current?.rows.filter(r=>view.cohort==='all'||r.group===view.cohort)||[],[current,view.cohort]);
  const rows=useMemo(()=>selected.filter(r=>(!query||`${r.ticker} ${r.name}`.toLowerCase().includes(query.toLowerCase()))&&(screen!=='weakening'||scope?.simultaneous_weakening.tickers.includes(r.ticker))&&(screen!=='paired'||typeof r.metrics[metric]?.change==='number'&&(!['operatingMargin','freeCashFlowMargin','cashToAssets'].includes(metric)||!r.financial))&&(screen!=='opposite'||(!['operatingMargin','freeCashFlowMargin','cashToAssets'].includes(metric)||!r.financial)&&typeof r.metrics[metric]?.change==='number'&&typeof r.event?.response_z==='number'&&r.metrics[metric].change!*r.event.response_z!<0)).sort((a,b)=>{
    const val=(r:UniverseRow)=>sort==='beta'?r.exposure?.beta:sort==='response'?r.event?.return:r.metrics[metric]?.change;
    if(sort==='ticker')return a.ticker.localeCompare(b.ticker);const av=val(a),bv=val(b);if(av==null)return bv==null?a.ticker.localeCompare(b.ticker):1;if(bv==null)return -1;return (sort==='lower'?av-bv:bv-av)||a.ticker.localeCompare(b.ticker);
  }),[selected,query,sort,screen,scope,metric]);
  const pages=Math.max(1,Math.ceil(rows.length/12)),visiblePage=Math.min(page,pages-1);
  const groups=current?Object.values(current.scopes).filter(g=>g.id!=='all'&&g.companies>0):[];
  function inspect(ticker:string){setDetail(ticker);onView({factorTicker:ticker});}
  useEffect(()=>{if(detail)detailRef.current?.scrollIntoView({behavior:'instant',block:'start'});},[detail]);
  function selectMetric(key:string){setMetric(key);setPage(0);setScreen('paired');constituentRef.current?.scrollIntoView({behavior:'instant',block:'start'});}
  function exportJson(){if(!current)return;downloadText(`factor-universe-${current.basis}-${day(current.sec_snapshot_at)}.json`,JSON.stringify({...current,selected_scope:view.cohort},null,2),'application/json');onNotice('Universe snapshot exported with definitions, coverage, and source links.');}
  function exportCsv(){if(!current)return;const quote=(v:unknown)=>`"${String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?`'${v}`:v??'').replaceAll('"','""')}"`;const lines=[['ticker','name','primary_group','basis','metric','current_percent','prior_percent','change_percentage_points','market_beta','beta_ci_low','beta_ci_high','price_model_observations','price_through','post_filing_20_session_model_adjusted_return_decimal','response_z','filing_date','fiscal_end','prior_fiscal_end','sec_source','sec_snapshot_at','methodology_version'],...rows.map(r=>[r.ticker,r.name,r.group,current.basis,metric,r.metrics[metric]?.current,r.metrics[metric]?.prior,r.metrics[metric]?.change,r.exposure?.beta,r.exposure?.beta_interval?.[0],r.exposure?.beta_interval?.[1],r.exposure?.observations,r.exposure?.through,r.event?.return,r.event?.response_z,r.filed,r.fiscal_end,r.prior_fiscal_end,r.source,current.sec_snapshot_at,current.methodology_version])];downloadText('factor-universe-screen.csv',lines.map(line=>line.map(quote).join(',')).join('\n'),'text/csv');onNotice(`${rows.length} visible-screen companies exported. Blank values are unavailable.`);}
  return <section className={s.lab} ref={rootRef} aria-label="Factor Lab universe research">
    {loading&&<p role="status" className={s.loading}><Loader2 size={18}/>Loading the prepared universe snapshot…</p>}
    {error&&<div role="alert" className={s.warning}><p>{error}</p><button className={s.button} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={15}/>Retry snapshot</button></div>}
    {current&&scope&&<>
      <div className={s.snapshotLine}><span><b>{scope.companies}</b> issuers in this scope</span><span>SEC snapshot <b>{day(current.sec_snapshot_at)}</b></span><span>Prices through <b>{day(current.price_through)}</b></span><span>{scope.exposure.eligible} price models available</span></div>
      {(current.status==='stale'||current.cache_status==='sec_only'||current.refresh_warning)&&<p className={s.warning} role="status">{current.refresh_warning||current.price_status||'Showing a retained snapshot. The original source dates remain visible; a scheduled refresh is pending.'}</p>}
      <section className={s.brief} aria-labelledby="universe-brief-heading"><div><span className={s.eyebrow}>Quantitative market briefing</span><h2 id="universe-brief-heading">What the covered universe is telling us</h2><ol>{scope.brief.map((item,i)=><li key={i}>{item}</li>)}</ol></div><aside><h3>How to read this snapshot</h3><p>Each company counts once. Higher and lower refer to changes from its own comparable prior-year period.</p><p>{current.basis==='ttm'?'TTM means the trailing 12 months; this compares two TTM periods ending about one year apart.':'Annual compares the latest annual period with the comparable prior year.'} Fiscal dates vary.</p><p>The universe is curated. These results do not describe every listed US company.</p></aside></section>
      <nav className={s.sectionTabs} aria-label="Factor Lab questions">{[['fundamentals','Fundamental breadth'],['behavior','Market behavior'],['research','Filing & price research']].map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</nav>
      {section==='fundamentals'&&<>
        <div className={s.sectionHeading}><div><h2>How broadly are fundamentals changing?</h2><p>Direction, magnitude and coverage. The bars count higher, lower and unchanged values among comparable issuers.</p></div></div>
        <div className={s.cards}>{scope.breadth.slice(0,4).map(m=><BreadthCard key={m.key} metric={m} onSelect={()=>selectMetric(m.key)}/>)}</div>
        <div className={s.pressure}><div><h3>Three measures declining together</h3><p>Slower revenue growth, lower operating margin and lower free cash flow margin in the same operating business.</p></div><strong>{scope.simultaneous_weakening.count}<small>of {scope.simultaneous_weakening.eligible} eligible</small></strong><button className={s.button} onClick={()=>{setScreen('weakening');setPage(0);constituentRef.current?.scrollIntoView({behavior:'instant'});}}>Review these issuers</button><p className={s.caption}>{scope.simultaneous_weakening.missing} operating issuers lack at least one required comparison. This combination calls for investigation; it is not a distress classification.</p></div>
        <section className={s.panel}><h2>Are company outcomes becoming more dispersed?</h2><p>The middle 50% range, or interquartile range (IQR), measures spread. Current and prior spreads below use exactly the same paired companies.</p><div className={s.tableWrap}><table><caption>Paired fundamental dispersion · all values in percentage points</caption><thead><tr><th>Measure</th><th>Paired issuers</th><th>Prior IQR</th><th>Current IQR</th><th>Change in spread</th><th>IQR of individual changes</th></tr></thead><tbody>{scope.breadth.map(m=><tr key={m.key}><th>{m.key==='revenueGrowth'?'Revenue growth':m.short}</th><td>{m.eligible}</td><td>{number(m.prior.iqr)}</td><td>{number(m.current.iqr)}</td><td>{m.paired_iqr_change==null?'Unavailable':`${number(Math.abs(m.paired_iqr_change))} ${m.paired_iqr_change>1e-9?'wider':m.paired_iqr_change< -1e-9?'narrower':'unchanged'}`}</td><td>{number(m.change.iqr)}</td></tr>)}</tbody></table></div><details><summary>What wider dispersion means</summary><p>A wider range means financial outcomes differ more across these companies than in their own comparable prior periods. It does not establish greater future stock returns or an opportunity for active managers. A larger IQR of changes means companies changed by more varied amounts.</p></details></section>
        <section className={s.panel}><h2>Where is the change concentrated?</h2><p>One primary research group per issuer, so the groups add to the universe. Group priority follows the published cohort order; these are research themes, not official industry sectors.</p><div className={s.tableWrap}><table><caption>Fundamental breadth by primary research group · higher / eligible</caption><thead><tr><th>Research group</th><th>Issuers</th><th>Growth acceleration</th><th>Operating margin</th><th>Free cash flow margin</th><th>Book equity / assets</th></tr></thead><tbody>{groups.map(g=><tr key={g.id} data-selected={view.cohort===g.id}><th><button className={s.textButton} onClick={()=>{onView({cohort:g.id});setPage(0);}}>{g.label}</button></th><td>{g.companies}</td>{g.breadth.slice(0,4).map(m=><td key={m.key}>{m.eligible?`${m.higher} / ${m.eligible}`:'—'}<small>{percent(m.higher_pct)}</small></td>)}</tr>)}</tbody></table></div></section>
        <details className={s.panel}><summary>Observed whole-universe history</summary><p>This history always covers all issuers, regardless of the selected group. Saved calculation snapshots begin when this dashboard is introduced. They are not point-in-time backtests. Changes in membership or eligible counts can change breadth.</p>{current.history.length<2?<p>History is beginning with this release. New scheduled SEC snapshots will add observations without inventing earlier values.</p>:<div className={s.tableWrap}><table><thead><tr><th>SEC snapshot</th><th>Universe issuers</th>{UNIVERSE_METRICS.slice(0,4).map(m=><th key={m.key}>{m.short} · higher / eligible</th>)}</tr></thead><tbody>{[...current.history].reverse().map(p=><tr key={p.sec_snapshot_at}><th>{day(p.sec_snapshot_at)}</th><td>{p.issuers.length}</td>{p.breadth.map(m=><td key={m.metric}>{m.higher} / {m.eligible}</td>)}</tr>)}</tbody></table></div>}</details>
      </>}
      {section==='behavior'&&<>
        <div className={s.sectionHeading}><div><h2>Where is market sensitivity concentrated?</h2><p>Daily log-return models over the latest 252 SPY intervals. Each included company needs at least 240 exact matches and the same final session.</p></div></div>
        {scope.exposure.coverage<.8&&<p className={s.warning}>Price-model coverage is {decimalPercent(scope.exposure.coverage)}. Treat these distributions as the available subset; coverage below 80% is insufficient for a broad exposure conclusion.</p>}
        <div className={s.cards}>{[['beta','Typical market beta','A slope of 1 means a 1% market move corresponds to roughly 1% of the stock’s fitted market component. This is the median issuer slope.'],['downside_beta','Typical down-market beta','Separate slopes fitted on SPY down days, requiring at least 30 observations. This does not measure the probability or maximum size of a loss.'],['r_squared','Typical variation explained','Median share of an issuer’s observed return variation explained by SPY. This is not forecast accuracy or the variance of the entire universe.'],['residual_volatility','Typical unexplained volatility','Median annualized standard deviation of issuer model residuals. Other influences remain after removing the fitted market component.']].map(([key,label,meaning])=><article className={s.breadthCard} key={key}><h3>{label}</h3><strong>{['r_squared','residual_volatility'].includes(key)?decimalPercent(scope.exposure.distributions[key].median):number(scope.exposure.distributions[key].median)}</strong><p>{scope.exposure.distributions[key].count} eligible models</p><p>{meaning}</p></article>)}</div>
        <div className={s.twoColumns}><section className={s.panel}><h2>Distribution of market beta</h2><p>Number of issuers in each sensitivity range. Negative beta means an inverse fitted market relationship.</p><div className={s.histogram}>{[[-Infinity,0,'Below 0'],[0,.75,'0 to <0.75'],[.75,1.25,'0.75 to <1.25'],[1.25,2,'1.25 to <2'],[2,Infinity,'2 or higher']].map(([lo,hi,label])=>{const count=selected.filter(r=>r.exposure&&r.exposure.beta>=Number(lo)&&r.exposure.beta<Number(hi)).length;return <div key={String(label)}><span>{label}</span><i style={{width:`${scope.exposure.eligible?count/scope.exposure.eligible*100:0}%`}}/><b>{count}</b></div>;})}</div><p className={s.caption}>These are descriptive bins, not risk ratings. Individual estimates and uncertainty remain available in the company drilldown.</p></section><section className={s.panel}><h2>Are stocks moving together?</h2><CoMovementChart data={scope.co_movement}/></section></div>
        <section className={s.panel}><h2>Exposure by primary research group</h2><div className={s.tableWrap}><table><thead><tr><th>Group</th><th>Price coverage</th><th>Median β</th><th>β middle 50% range</th><th>Median downside β</th><th>Independent sector sensitivity</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><th>{g.label}</th><td>{g.exposure.eligible} / {g.companies}</td><td>{number(g.exposure.distributions.beta.median)}</td><td>{number(g.exposure.distributions.beta.q25)} to {number(g.exposure.distributions.beta.q75)}</td><td>{number(g.exposure.distributions.downside_beta.median)}<small>{g.exposure.distributions.downside_beta.count} models</small></td><td>{number(g.exposure.distributions.sector_beta.median)}<small>{g.exposure.distributions.sector_beta.count} models</small></td></tr>)}</tbody></table></div><p className={s.caption}>Independent sector sensitivity uses each group’s sector ETF after removing its fitted SPY component. ETF choices are disclosed in constituent exports; slopes against different ETFs need context.</p></section>
      </>}
      {section==='research'&&<>
        <section className={s.panel}><div className={s.sectionHeading}><div><h2>Do filing changes and price responses point in the same direction?</h2><p>Horizontal: absolute change in the selected filing measure. Vertical: standardized model-adjusted response over the first 20 eligible post-filing sessions.</p></div><label>Filing measure<select value={metric} onChange={e=>{setMetric(e.target.value);setPage(0);}}>{UNIVERSE_METRICS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label></div><FilingMap rows={selected} metric={metric} onCompany={inspect}/><p>Higher filing measures do not always mean better business performance. The response is relative to a pre-event market-and-sector model and may reflect other news. Select a point to investigate its filing and price evidence.</p><button className={s.button} onClick={()=>{setScreen('opposite');setPage(0);constituentRef.current?.scrollIntoView({behavior:'instant'});}}>Inspect opposite directions</button></section>
        <section className={s.panel}><h2>Characteristic research: an observed association</h2><p>Do larger filing changes tend to accompany larger standardized post-filing responses? Spearman correlation compares ranks and ranges from −1 to +1. At least 12 paired observations are required.</p><div className={s.tableWrap}><table><thead><tr><th>Filing change</th><th>Paired events</th><th>Rank correlation</th><th>Filing dates represented</th></tr></thead><tbody>{scope.associations.map(a=><tr key={a.metric}><th>{a.label}</th><td>{a.observations}</td><td>{a.rho===null?'Unavailable':number(a.rho)}</td><td>{day(a.filing_dates.earliest)} to {day(a.filing_dates.latest)}</td></tr>)}</tbody></table></div><details><summary>What these associations can establish</summary><p>A positive value describes a tendency for larger filing changes to accompany larger responses in this sample. The events occur on different dates, share market conditions, and mix businesses. These are unadjusted descriptive associations; no significance, causality, predictive ability or investable factor premium is claimed.</p><p>Historical factor returns require a point-in-time universe and portfolio-formation history. This snapshot does not reconstruct those from today’s company list.</p></details></section>
      </>}
      <section className={s.panel} ref={constituentRef} aria-labelledby="universe-constituents-heading"><h2 id="universe-constituents-heading">Inspect the companies behind the result</h2><p>Start with the market pattern, then open an issuer when you need its sources and full diagnostics.</p><div className={s.filters}><label>Find a company<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Ticker or name"/></label><label>Filing measure<select value={metric} onChange={e=>{setMetric(e.target.value);setPage(0);}}>{UNIVERSE_METRICS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Order<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="change">Largest filing increase</option><option value="lower">Largest filing decrease</option><option value="beta">Highest market beta</option><option value="response">Highest post-filing response</option><option value="ticker">Ticker</option></select></label><label>Screen<select value={screen} onChange={e=>{setScreen(e.target.value);setPage(0);}}><option value="all">All in scope</option><option value="paired">Comparable filing pairs</option><option value="weakening">Three measures declining</option><option value="opposite">Filing / response opposite signs</option></select></label></div>
        <div className={s.tableWrap}><table><caption>{rows.length} issuers · filing changes in percentage points · — means unavailable</caption><thead><tr><th>Company</th><th>Filing change</th><th>Market β</th><th>20-session model-adjusted return</th><th>Filed</th><th>Evidence</th></tr></thead><tbody>{rows.slice(visiblePage*12,visiblePage*12+12).map(r=><tr key={r.ticker}><th><button className={s.textButton} onClick={()=>inspect(r.ticker)}>{r.ticker}</button><small>{r.name}</small></th><td>{signed(r.metrics[metric]?.change)}<small>{r.metrics[metric]?.unavailable_reason==='ISSUER_TYPE_EXCLUDED'?'Excluded issuer type':<>{number(r.metrics[metric]?.prior)} → {number(r.metrics[metric]?.current)}</>}</small></td><td>{number(r.exposure?.beta)}</td><td>{decimalPercent(r.event?.return)}<small>{r.event?`through ${r.event.through}`:'Price response unavailable'}</small></td><td>{day(r.filed)}<small>Period {day(r.fiscal_end)}</small></td><td>{r.source&&<a href={r.source} target="_blank" rel="noreferrer">SEC filing <ExternalLink size={12}/></a>}<button className={s.textButton} onClick={()=>inspect(r.ticker)}>Full diagnostics</button></td></tr>)}</tbody></table></div>
        {!rows.length&&<p className={s.empty}>No issuers match this screen. Change the filter or clear the search.</p>}<div className={s.pagination}><span>Page {visiblePage+1} of {pages}</span><button className={s.button} disabled={visiblePage===0} onClick={()=>setPage(visiblePage-1)}>Previous</button><button className={s.button} disabled={visiblePage+1===pages} onClick={()=>setPage(visiblePage+1)}>Next</button><button className={s.button} onClick={exportCsv}><Download size={15}/>Screen CSV</button></div>
      </section>
      {detail&&<section className={s.drilldown} ref={detailRef} aria-label={`${detail} company drilldown`}><button className={s.button} onClick={()=>{setDetail(null);constituentRef.current?.scrollIntoView({behavior:'instant'});}}><ArrowLeft size={16}/>Return to universe research</button><p className={s.caption}>Universe exposure uses 252 SPY intervals. The company drilldown uses the selected calendar-year window ({view.factorWindow}) and may produce different estimates; its exact sample is disclosed.</p><CompanyLab key={detail} companies={atlas?.companies||current.rows} basis={view.basis} cohortId="all" factorTicker={detail} factorWindow={view.factorWindow} factorSector={view.factorSector} onView={patch=>{onView(patch);if(patch.factorTicker)setDetail(patch.factorTicker);}} onNotice={onNotice}/></section>}
      <section className={s.handoff}><div><h2>Use this snapshot in your research</h2><p>The export includes every issuer, definitions, eligibility counts, filing links, source dates and interpretation limits. Your AI assistant receives the same evidence as this page.</p></div><div className={s.actions}><button className={s.button} onClick={exportJson}><Download size={16}/>Universe JSON</button><button className={s.button} onClick={()=>{downloadText('factor-universe-brief.md',universeMarkdown(current,view.cohort),'text/markdown');onNotice('Market research brief exported.');}}><Download size={16}/>Research brief</button><a className={s.button} href="/market/factors">Methodology</a></div></section>
      <details className={s.panel}><summary>Coverage, grouping and interpretation limits</summary><p>{current.universe.issuers} unique issuers loaded from {current.universe.requested} curated ticker entries; {current.universe.share_classes_excluded} duplicate share classes excluded. SEC observed {current.sec_snapshot_at}; aggregate calculated {current.generated_at}.</p><ul>{current.limitations.map(line=><li key={line}>{line}</li>)}</ul><p>Schema {current.schema_version} · Method {current.methodology_version}</p></details>
    </>}
  </section>;
}
