export type RiskSource = { tag: string; label?: string; value: number | null; unit?: string; start?: string | null; end: string; filed?: string; accession?: string; url?: string; documentUrl?: string; revised?: boolean; sourceCik?: string; sourceType?: string; scopeNote?: string };
export type RiskPoint = { fy: number; fp: string; kind: string; end: string; value: number | null; sources: RiskSource[]; formula?: string; calculations?: any[] };
export type RiskMetric = { id: string; label: string; pillar: string; format: string; value: number | null; prior: number | null; delta: number | null; zone: { level: string; label: string }; why: string; note?: string; question: string; formula: string; inputs: { label: string; value: number | null }[]; calculations: any[]; series: RiskPoint[]; sources: RiskSource[]; thresholds: string | null; classification: string; trajectory?: { direction: string; steps: number } };
export type RiskProfile = { basis: string; periods: (RiskPoint & { filed?: string; form?: string; accession?: string })[]; industry: { isBank: boolean; isFinancial: boolean; isBrokerDealer?: boolean; isInsurer?: boolean; group?: string; label: string }; metrics: RiskMetric[]; watchItems: { id: string; label: string; severity: string; pillar: string; reason: string; question: string }[]; coverage: { available: number; total: number; missing: string[] }; stressInputs: Record<string, { value: number | null; formula?: string; sources: RiskSource[] }>; reportedFlows?: Record<string, RiskPoint[]>; reportedBalances?: Record<string, RiskPoint[]>; zScore: any; models: { zmijewski: any; beneish: any }; notes: string[] };
export type RiskMaturityProfile = {
  status: string; asOf: string | null; filedAt: string | null; form: string | null; sourceUrl: string; basis: string | null;
  totalScheduled: number | null; reportedSubtotal: number | null;
  buckets: { key: string; label: string; value: number | null; calendarYear: number | null; startDate: string; endDate: string | null; dateBasis: string; tag: string }[];
  metrics: Record<string, { value: number | null; startDate: string | null; endDate: string | null; formula?: string }>;
  coverage: { reportedBuckets: number; totalBuckets: number; complete: boolean }; warnings: string[];
};
export type RiskData = { ticker: string; cik: string; companyName: string; sic: string; sicDescription: string; current: RiskProfile; annual: RiskProfile; generatedAt: string; refinancing?: RiskMaturityProfile; sourceCoverage?: { companyFactsThrough?: string | null; latestFilingReportDate?: string | null; notices?: string[]; filingFallback?: { status: string; reportDate?: string | null; documentUrl?: string | null; addedFacts?: number }; continuity?: { status: string; sourceUrl?: string | null; effectiveDate?: string | null; predecessorCiks?: string[] } } };
