'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDownToLine, ArrowUpRight, Check, Link2, RefreshCw } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ASSETS, MEASURES, DTCC_LINKS, NYFED_TERMS, SWAPS_HOME, SWAPS_NOTES } from '../../../utils/marketPlumbing/catalog.js';
import { compactNumber, fundingSeries, parsePlumbingView, plumbingPath, snapshotAge, swapView } from '../../../utils/marketPlumbing/model.js';
import { validSnapshot } from '../../../utils/marketPlumbing/normalize.js';
import s from './research.module.css';

const COLORS = ['var(--r-teal)', 'var(--r-violet)', 'var(--r-gold)', 'var(--r-green)', 'var(--r-pink)', 'var(--r-blue)', 'var(--r-gray)'];
const dateLabel = date => new Date(`${date}T12:00:00Z`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
const tickDate = date => new Date(`${date}T12:00:00Z`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' });
const pct = n => n == null ? '—' : `${n.toFixed(2)}%`;
const signed = (n, suffix = '') => n == null ? '—' : `${n > 0 ? '+' : ''}${n.toLocaleString('en-US', { maximumFractionDigits: 2 })}${suffix}`;
const chartMargins = { top: 12, right: 12, bottom: 0, left: 0 };
const axis = { tick: { fill: 'var(--r-muted)', fontSize: 12 }, axisLine: false, tickLine: false, minTickGap: 36 };
function ChartTip({ active, payload, label, formatter = compactNumber }) {
  if (!active || !payload?.length) return null;
  return <div className={s.tooltip}><b>{/^\d{4}-\d{2}-\d{2}$/.test(String(label)) ? dateLabel(label) : label}</b>{payload.filter(p => p.value != null).map(p => <span key={p.dataKey}><i style={{ background: p.color || p.fill }} />{p.name}<strong>{formatter(Number(p.value))}</strong></span>)}</div>;
}
function ChartHeader({ title, meta, children }) { return <div className={s.chartHeader}><div><h2>{title}</h2>{meta && <p>{meta}</p>}</div>{children}</div>; }
function Metric({ label, value, detail, accent }) { return <div className={s.metric}><span>{label}</span><strong style={accent ? { color: accent } : undefined}>{value}</strong><small>{detail}</small></div>; }
function Note({ title = 'How to read this chart', children }) { return <details className={s.note}><summary>{title}</summary><div>{children}</div></details>; }

export default function MarketResearch({ kind, initialData, cftcEnabled = true }) {
  const [data, setData] = useState(initialData), [view, setView] = useState(() => parsePlumbingView('', kind));
  const [notice, setNotice] = useState(''), [copyLink, setCopyLink] = useState(''), [loading, setLoading] = useState(false), [retry, setRetry] = useState(0), [error, setError] = useState(false);
  useEffect(() => { const restore = () => setView(parsePlumbingView(window.location.search, kind)); restore(); window.addEventListener('popstate', restore); return () => window.removeEventListener('popstate', restore); }, [kind]);
  useEffect(() => {
    const controller = new AbortController(); let active = true;
    setLoading(true);
    const timeout = setTimeout(() => controller.abort(), 25000);
    fetch(`/api/market-plumbing?view=${kind}`, { signal: controller.signal }).then(async response => {
      const result = await response.json(); if (!response.ok || !validSnapshot(result, kind)) throw new Error();
      if (active) { setData(result); setError(false); }
    }).catch(() => { if (active) setError(true); }).finally(() => { clearTimeout(timeout); if (active) setLoading(false); });
    return () => { active = false; clearTimeout(timeout); controller.abort(); };
  }, [kind, retry]);
  function update(patch) {
    const next = { ...view, ...patch }; window.history.pushState(null, '', plumbingPath(next)); setView(next); setNotice('');
  }
  async function share() {
    const url = `${window.location.origin}${plumbingPath(view)}`;
    try { await navigator.clipboard.writeText(url); setNotice('View link copied'); setCopyLink(''); }
    catch { setCopyLink(url); }
  }
  const stale = snapshotAge(data), retained = data.availability === 'retained';
  return <div className={s.page}>
    <div className={s.breadcrumb}><Link href="/market">Market</Link><span>/</span><span>{kind === 'funding' ? 'Funding & Clearing' : 'Derivatives'}</span></div>
    <header className={s.header}><div><h1>{kind === 'funding' ? 'Funding & clearing' : 'Derivatives explorer'}</h1><p>{kind === 'funding' ? 'Repo conditions and Treasury settlement across the market.' : 'The swaps market through activity, composition, and clearing.'}</p></div><button className={s.button} onClick={share}><Link2 size={15} />Share view</button></header>
    <nav className={s.nav} aria-label="Market sections"><Link href="/market">Market Briefing</Link>{cftcEnabled && <Link href="/market?tab=positioning">CFTC Positioning</Link>}<Link href="/market?tab=sectors">Sector Performance</Link><Link href="/market/funding" aria-current={kind === 'funding' ? 'page' : undefined}>Funding & Clearing</Link><Link href="/market/derivatives" aria-current={kind === 'derivatives' ? 'page' : undefined}>Derivatives</Link></nav>
    {notice && <p className={s.notice} role="status"><Check size={14} />{notice}</p>}
    {copyLink && <label className={s.copyLabel}>Copy view link<input readOnly value={copyLink} onFocus={e => e.target.select()} /></label>}
    <div className={s.sourceLine}><span>{kind === 'funding' ? 'Federal Reserve Bank of New York' : 'CFTC Weekly Swaps Report'}<b>Aggregate market data</b></span><span>{loading ? 'Checking for an updated snapshot…' : `Source capture ${dateLabel(data.generatedAt.slice(0, 10))}`}</span></div>
    {(error || stale || retained) && <div className={s.status} role="status"><span>{stale ? 'This saved snapshot has not been checked recently.' : 'Showing the last verified source capture.'} Report dates remain visible below.</span><button onClick={() => setRetry(n => n + 1)} disabled={loading}><RefreshCw size={13} />{loading ? 'Checking…' : 'Check snapshot'}</button></div>}
    {kind === 'funding' ? <Funding data={data} view={view} update={update} /> : <Derivatives data={data} view={view} update={update} />}
    <div className={s.researchLinks}><Link href="/analysis/banks">Explore individual banks in BankScope <ArrowUpRight size={16} /></Link><span>Market aggregates describe the wider environment. Bank financial statements identify each legal entity separately.</span></div>
    <details className={s.sources}><summary>Sources, coverage & publication notes</summary><div>
      {kind === 'funding' ? <>
        <p>SOFR, BGCR, and TGCR are distinct, overlapping Treasury repo benchmarks. Volumes are not added together. The SOFR − TGCR spread and basis-point changes are EDGAR Terminal calculations. Rate observations use their effective dates.</p>
        <p>Treasury fails combine nominal Treasury and TIPS series. Each weekly observation is the cumulative amount reported by primary dealers; delivery and receipt fails overlap and are kept separate. These are not DTCC’s daily FICC fails, losses, or a bank-specific exposure.</p>
        <p><a href="https://www.newyorkfed.org/markets/reference-rates" target="_blank" rel="noreferrer">Reference-rate methodology ↗</a> · <a href="https://www.newyorkfed.org/markets/pridealers_failsprimer.html" target="_blank" rel="noreferrer">Primary-dealer fails guide ↗</a></p>
      </> : <>
        <p>The CFTC aggregates market-facing swaps reported to swap data repositories. This view uses the CFTC’s published aggregate tables. It is separate from DTCC’s transaction-level dissemination feed and from CFTC futures positioning.</p>
        <p>Notional outstanding is a stock at the report date. Weekly notional traded and trade count measure activity during the reporting week. Notional is neither market value nor counterparty credit exposure. Cleared data use the source’s single-count convention; participant tables, which count counterparties differently, are excluded.</p>
        <p>Publication normally follows the reporting week by about two and a half weeks. Five initial aggregate reporting periods are available; product-level history begins with retained detailed reports. Small discrepancies between published totals and their components are retained. Missing values stay unavailable.</p>
        <p>Interest-rate tenor labels are in months and follow CFTC’s published buckets, including its boundary adjustment. FX uses calendar days and different buckets for outstanding versus activity. Credit tables provide grade, not currency or tenor. Currency and tenor breakdowns are separate views of the same total and must not be added together.</p>
        <p><a href={SWAPS_HOME} target="_blank" rel="noreferrer">CFTC Weekly Swaps Report ↗</a> · <a href={SWAPS_NOTES} target="_blank" rel="noreferrer">Explanatory notes ↗</a> · <a href="https://www.cftc.gov/MarketReports/SwapsReports/DataDictionary/index.htm" target="_blank" rel="noreferrer">Data dictionary ↗</a> · <a href="https://pddata.dtcc.com/" target="_blank" rel="noreferrer">DTCC transaction dashboard ↗</a></p>
      </>}
      <ul>{data.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{new URL(source.url).pathname.split('/').at(-1)} ↗</a><span>Retrieved {dateLabel(source.retrievedAt.slice(0, 10))} · {source.acquisition === 'official-page-web-retrieval' ? 'Official page capture' : 'Official data feed'}</span></li>)}</ul>
      <a href={`/api/market-plumbing?view=${kind}`} target="_blank" rel="noreferrer">Prepared research data · JSON ↗</a>
    </div></details>
    {kind === 'funding' && <footer className={s.attribution}><p>© {data.generatedAt.slice(0, 4)} Federal Reserve Bank of New York. Content from the New York Fed subject to the <a href={NYFED_TERMS} target="_blank" rel="noreferrer">Terms of Use at newyorkfed.org</a>.</p><p>The reference-rate data are subject to those Terms of Use. The New York Fed is not responsible for publication of the reference-rate data by EDGAR Terminal, does not endorse any particular republication, and has no liability for your use.</p></footer>}
  </div>;
}

function Funding({ data, view, update }) {
  const series = useMemo(() => fundingSeries(data, view.range), [data, view.range]);
  const [visible, setVisible] = useState(['SOFR', 'TGCR', 'BGCR']);
  const last = series.latest, prior = series.prior, fail = series.fails.at(-1);
  const change = last?.SOFR != null && prior?.SOFR != null ? Math.round((last.SOFR - prior.SOFR) * 10000) / 100 : null;
  const rateColors = { SOFR: COLORS[0], TGCR: COLORS[2], BGCR: COLORS[1] };
  return <>
    <div className={s.controls}><span>Daily rates through <b>{dateLabel(last.date)}</b></span><div className={s.segments} aria-label="Chart history">{[['1m', '1 month'], ['3m', '3 months'], ['1y', '1 year']].map(([id, label]) => <button key={id} aria-pressed={view.range === id} onClick={() => update({ range: id })}>{label}</button>)}</div></div>
    <div className={s.metrics}><Metric label="SOFR" value={pct(last.SOFR)} detail="Secured Overnight Financing Rate" accent={COLORS[0]} /><Metric label="Daily rate change" value={signed(change, ' bp')} detail={prior ? `From ${dateLabel(prior.date)}` : 'Prior observation unavailable'} /><Metric label="SOFR transaction volume" value={compactNumber(last.volume == null ? null : last.volume * 1000)} detail="Underlying daily repo activity" /><Metric label="SOFR − TGCR" value={signed(last.SOFR != null && last.TGCR != null ? (last.SOFR - last.TGCR) * 100 : null, ' bp')} detail="Spread between reported benchmarks" accent={COLORS[2]} /></div>
    <section className={s.primaryChart}><ChartHeader title="The cost of overnight funding" meta="Annualized rate · percent"><div className={s.legend}>{Object.keys(rateColors).map(name => <button key={name} aria-pressed={visible.includes(name)} onClick={() => setVisible(current => current.includes(name) ? current.length > 1 ? current.filter(v => v !== name) : current : [...current, name])}><i style={{ background: rateColors[name] }} />{name}</button>)}</div></ChartHeader>
      <div className={s.chartLarge} role="img" aria-label="SOFR, TGCR, and BGCR daily rate history. Exact values are available in the expandable data table."><ResponsiveContainer width="100%" height="100%"><LineChart data={series.rates} margin={chartMargins}><CartesianGrid stroke="var(--r-line)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="date" tickFormatter={tickDate} {...axis} /><YAxis {...axis} domain={['auto', 'auto']} tickFormatter={v => `${Number(v).toFixed(2)}%`} width={65} /><Tooltip content={<ChartTip formatter={pct} />} />{visible.map(name => <Line key={name} name={name} dataKey={name} type="linear" stroke={rateColors[name]} strokeWidth={name === 'SOFR' ? 2.5 : 1.7} dot={false} activeDot={{ r: 4 }} connectNulls={false} isAnimationActive={false} />)}</LineChart></ResponsiveContainer></div>
      <Note><p>SOFR covers a broader Treasury repo market. TGCR measures tri-party general collateral repo; BGCR adds GCF repo activity. Click the legend to focus on a benchmark. Differences reflect market coverage and conditions, not a direct measure of a bank’s funding cost.</p></Note>
    </section>
    <div className={s.twoCharts}><section><ChartHeader title="Repo activity" meta="SOFR underlying volume · USD" /><div className={s.chartSmall} role="img" aria-label="Daily transaction volume underlying SOFR"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series.rates} margin={chartMargins}><defs><linearGradient id="repo-volume-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={COLORS[0]} stopOpacity={0.28} /><stop offset="100%" stopColor={COLORS[0]} stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--r-line)" strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={tickDate} {...axis} /><YAxis {...axis} tickFormatter={v => compactNumber(v * 1000, 'volume', 1)} width={62} /><Tooltip content={<ChartTip formatter={v => compactNumber(v * 1000)} />} /><Area name="SOFR repo volume" dataKey="volume" type="linear" stroke={COLORS[0]} fill="url(#repo-volume-fill)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div></section>
      <section><ChartHeader title="Funding spread" meta="SOFR minus TGCR · basis points" /><div className={s.chartSmall} role="img" aria-label="Daily difference between SOFR and TGCR in basis points"><ResponsiveContainer width="100%" height="100%"><BarChart data={series.rates} margin={chartMargins}><CartesianGrid vertical={false} stroke="var(--r-line)" strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={tickDate} {...axis} /><YAxis {...axis} tickFormatter={v => `${v} bp`} width={62} /><Tooltip content={<ChartTip formatter={v => signed(v, ' bp')} />} /><Bar dataKey="spread" name="SOFR − TGCR" fill={COLORS[2]} radius={[2, 2, 0, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></section></div>
    <section className={s.fails}><ChartHeader title="Treasury settlement fails" meta={`Primary dealers · cumulative weekly amounts · ${fail ? `through ${dateLabel(fail.date)}` : 'No observations in this range'}`} /><div className={s.failLayout}><div className={s.failNumbers}><Metric label="Fails to deliver" value={compactNumber(fail?.deliver)} detail="Nominal Treasuries + TIPS" accent={COLORS[1]} /><Metric label="Fails to receive" value={compactNumber(fail?.receive)} detail="Shown separately to avoid double counting" accent={COLORS[0]} /></div><div className={s.chartSmall} role="img" aria-label="Primary-dealer Treasury fails to deliver and receive by reporting week"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series.fails} margin={chartMargins}><CartesianGrid vertical={false} stroke="var(--r-line)" strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={tickDate} {...axis} /><YAxis {...axis} tickFormatter={v => compactNumber(v, 'volume', 0)} width={68} /><Tooltip content={<ChartTip />} /><Area name="Fails to deliver" dataKey="deliver" stroke={COLORS[1]} fill={COLORS[1]} fillOpacity={0.08} isAnimationActive={false} /><Area name="Fails to receive" dataKey="receive" stroke={COLORS[0]} fill="transparent" strokeDasharray="5 3" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div></div>
      <Note title="What a settlement fail means"><p>A fail means securities were not delivered on the agreed settlement date. These weekly cumulative figures can include the same unsettled obligation on several days. They are not a default count, realized loss, or a measure of unique failed trades.</p></Note></section>
    <section className={s.external}><ChartHeader title="FICC & DTCC source reports" meta="Additional coverage on the publisher’s website" /><div>{DTCC_LINKS.map(link => <a href={link.href} key={link.href} target="_blank" rel="noreferrer"><span>{link.label}<small>{link.detail}</small></span><ArrowUpRight size={18} /></a>)}</div></section>
    <ExactFunding series={series} data={data} />
  </>;
}

function Derivatives({ data, view, update }) {
  const value = useMemo(() => swapView(data, view), [data, view]);
  const changeLabel = value.previousDate ? `From ${dateLabel(value.previousDate)}` : 'Prior comparable period unavailable';
  const canTrend = value.trend.filter(p => p.value !== null).length >= 2;
  const dimension = view.asset === 'credit' ? 'grade' : 'currency';
  const compositionRows = value[dimension];
  return <>
    <div className={s.assetTabs} aria-label="Swap asset class">{Object.entries(ASSETS).map(([id, label]) => <button key={id} aria-pressed={view.asset === id} onClick={() => update({ asset: id, product: 'TOTAL', date: '' })}>{label}</button>)}</div>
    <div className={s.filters}><label>Measure<select value={view.measure} onChange={e => update({ measure: e.target.value, product: 'TOTAL', date: '' })}>{Object.entries(MEASURES).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Reporting week<select value={value.date} onChange={e => update({ date: e.target.value, product: 'TOTAL' })}>{[...value.dates].reverse().map(date => <option key={date} value={date}>{dateLabel(date)}</option>)}</select></label><label>Product<select value={value.product} onChange={e => update({ product: e.target.value })}><option value="TOTAL">All products</option>{value.products.map(product => <option key={product} value={product}>{product}</option>)}</select></label><div className={s.scope}><b>{ASSETS[view.asset]}</b><span>{value.product === 'TOTAL' ? 'All reported products' : value.product} · Week ended {dateLabel(value.date)}</span></div></div>
    <div className={s.metrics}><Metric label={MEASURES[view.measure]} value={compactNumber(value.total, view.measure)} detail={view.measure === 'outstanding' ? 'Gross notional · USD' : view.measure === 'tickets' ? 'Market-facing new trades' : 'Reported notional · USD'} accent={COLORS[0]} /><Metric label="Change from prior period" value={signed(value.change, '%')} detail={changeLabel} /><Metric label="Centrally cleared" value={value.share == null ? '—' : `${value.share.toFixed(1)}%`} detail="Share of this measure and product" accent={COLORS[1]} /></div>
    <div className={s.derivativeLead}><section><ChartHeader title={view.measure === 'outstanding' ? 'The reported market over time' : 'Activity over the available weeks'} meta={`${value.product === 'TOTAL' ? 'All products' : value.product} · ${MEASURES[view.measure]}`} />{canTrend ? <div className={s.chartMedium} role="img" aria-label={`${MEASURES[view.measure]} across reporting weeks`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={value.trend} margin={chartMargins}><CartesianGrid stroke="var(--r-line)" vertical={false} strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={tickDate} {...axis} /><YAxis {...axis} tickFormatter={v => compactNumber(v, view.measure, 1)} width={70} /><Tooltip content={<ChartTip formatter={v => compactNumber(v, view.measure)} />} /><Area name={MEASURES[view.measure]} dataKey="value" stroke={COLORS[0]} strokeWidth={2.5} fill={COLORS[0]} fillOpacity={0.1} connectNulls={false} isAnimationActive={false} dot={{ r: 3, strokeWidth: 0, fill: COLORS[0] }} /></AreaChart></ResponsiveContainer></div> : <div className={s.empty}><b>{compactNumber(value.total, view.measure)}</b><p>One retained period for this product. A trend needs at least two.</p><button className={s.button} onClick={() => update({ product: 'TOTAL' })}>View the full asset-class history</button></div>}</section>
      <section className={s.clearing}><ChartHeader title="Clearing mix" meta="Same selection · single-count basis" /><div className={s.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{ name: 'Cleared', value: value.cleared || 0 }, { name: 'Uncleared', value: value.uncleared || 0 }]} dataKey="value" innerRadius="67%" outerRadius="90%" startAngle={90} endAngle={-270} paddingAngle={2} stroke="none" isAnimationActive={false}><Cell fill={COLORS[1]} /><Cell fill="var(--r-donut-muted)" /></Pie><Tooltip content={<ChartTip formatter={v => compactNumber(v, view.measure)} />} /></PieChart></ResponsiveContainer><div><strong>{value.share == null ? '—' : `${value.share.toFixed(1)}%`}</strong><span>cleared</span></div></div><dl className={s.mixLabels}><div><dt><i style={{ background: COLORS[1] }} />Cleared</dt><dd>{compactNumber(value.cleared, view.measure)}</dd></div><div><dt><i style={{ background: 'var(--r-donut-muted)' }} />Uncleared</dt><dd>{compactNumber(value.uncleared, view.measure)}</dd></div></dl></section></div>
    <div className={s.breakdowns}><section><ChartHeader title="Product composition" meta="All products in the selected asset class" /><HorizontalBars rows={value.composition} measure={view.measure} selected={value.product} onSelect={product => update({ product: value.product === product ? 'TOTAL' : product })} empty="Product detail was not retained for this reporting week." /></section><section><ChartHeader title={dimension === 'grade' ? 'Credit grade' : view.asset === 'fx' ? 'Currency-pair groups' : 'Currency composition'} meta={`${value.product === 'TOTAL' ? 'All products' : value.product} · ${dimension === 'grade' ? 'CFTC grade categories' : view.measure === 'tickets' ? 'Reported trade count' : 'Amounts expressed in USD'}`} /><HorizontalBars rows={compositionRows} measure={view.measure} empty="This breakdown is not available for the selected product and period." /></section></div>
    {view.asset !== 'credit' && <section className={s.tenor}><ChartHeader title="Tenor profile" meta={`${value.product === 'TOTAL' ? 'All products' : value.product} · ${view.asset === 'fx' ? 'calendar days' : 'months, using CFTC bucket conventions'}`} />{value.tenor.length ? <div className={s.chartSmall} role="img" aria-label="Reported swaps across tenor buckets"><ResponsiveContainer width="100%" height="100%"><BarChart data={value.tenor} margin={chartMargins}><CartesianGrid vertical={false} stroke="var(--r-line)" strokeDasharray="3 5" /><XAxis dataKey="name" {...axis} /><YAxis {...axis} tickFormatter={v => compactNumber(v, view.measure, 1)} width={70} /><Tooltip content={<ChartTip formatter={v => compactNumber(v, view.measure)} />} /><Bar dataKey="value" name={MEASURES[view.measure]} radius={[4, 4, 0, 0]} maxBarSize={75} isAnimationActive={false}>{value.tenor.map((row, i) => <Cell key={row.name} fill={COLORS[i % COLORS.length]} />)}</Bar></BarChart></ResponsiveContainer></div> : <p className={s.emptyText}>Tenor detail was not retained for this selection.</p>}<Note><p>Tenor buckets are those published by the CFTC. Interest-rate labels are in months; FX labels are in days and differ between outstanding positions and weekly activity. They are not contractual cash-flow forecasts.</p></Note></section>}
    <ExactSwaps data={data} view={view} value={value} />
  </>;
}
function HorizontalBars({ rows, measure, selected, onSelect, empty }) {
  const sorted = [...rows].sort((a, b) => (b.value ?? -1) - (a.value ?? -1));
  const max = Math.max(1, ...rows.map(row => row.value || 0));
  if (!rows.length) return <p className={s.emptyText}>{empty}</p>;
  return <div className={s.bars}>{sorted.map((row, i) => {
    const content = <><span>{row.name}<b>{compactNumber(row.value, measure)}</b></span><div className={s.track}><i style={{ width: `${Math.max(0, (row.value || 0) / max * 100)}%`, background: COLORS[i % COLORS.length] }} /></div></>;
    return onSelect ? <button key={row.name} aria-pressed={selected === row.name} onClick={() => onSelect(row.name)}>{content}</button> : <div key={row.name}>{content}</div>;
  })}</div>;
}
function downloadCsv(name, headers, rows) {
  const cell = value => { let text = value == null ? '' : String(value); if (/^[=+@-]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; };
  const blob = new Blob(['\uFEFF', [headers, ...rows].map(row => row.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function ExactFunding({ series, data }) {
  const headers = ['Date', 'SOFR (%)', 'TGCR (%)', 'BGCR (%)', 'SOFR volume (USD billions)', 'SOFR minus TGCR (bp)'];
  const rows = series.rates.map(r => [r.date, r.SOFR, r.TGCR, r.BGCR, r.volume, r.spread]);
  return <details className={s.exact}><summary>Inspect & download the figures</summary><div className={s.tableActions}><span>{rows.length} rate observations · missing values are blank</span><button className={s.button} onClick={() => downloadCsv('funding-rates.csv', [...headers, 'Source', 'Terms & notice'], rows.map(row => [...row, data.sources.find(source => source.url.includes('/rates/'))?.url, `© ${data.generatedAt.slice(0, 4)} Federal Reserve Bank of New York. Subject to ${NYFED_TERMS}. The New York Fed is not responsible for publication of the reference-rate data by EDGAR Terminal, does not endorse any particular republication, and has no liability for your use. Spread calculated by EDGAR Terminal.`]))}><ArrowDownToLine size={14} />Rates CSV</button><button className={s.button} onClick={() => downloadCsv('treasury-fails.csv', ['Week ending', 'Fails to deliver (USD millions)', 'Fails to receive (USD millions)', 'Basis', 'Source', 'Terms'], series.fails.map(r => [r.date, r.deliver, r.receive, 'Primary dealers; cumulative weekly; nominal Treasury + TIPS', data.sources.find(source => source.url.includes('/pd/'))?.url, `© ${data.generatedAt.slice(0, 4)} Federal Reserve Bank of New York. Subject to ${NYFED_TERMS}.`]))}><ArrowDownToLine size={14} />Fails CSV</button></div><div className={s.tableScroll}><table><caption>Reference rates and EDGAR Terminal’s calculated spread</caption><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{[...rows].reverse().map(row => <tr key={row[0]}>{row.map((v, i) => <td key={i}>{v == null ? '—' : v}</td>)}</tr>)}</tbody></table></div><div className={s.tableScroll}><table><caption>Primary-dealer Treasury settlement fails · cumulative weekly · USD millions</caption><thead><tr><th>Week ending</th><th>Fails to deliver</th><th>Fails to receive</th></tr></thead><tbody>{[...series.fails].reverse().map(row => <tr key={row.date}><td>{row.date}</td><td>{row.deliver ?? '—'}</td><td>{row.receive ?? '—'}</td></tr>)}</tbody></table></div></details>;
}
function ExactSwaps({ data, view, value }) {
  const rows = data.observations.filter(r => r.asset === view.asset && r.measure === view.measure && r.product === value.product);
  const unit = view.measure === 'tickets' ? 'Trades' : 'USD millions';
  const headers = ['Week ending', 'Product', 'Breakdown', 'Category', unit];
  return <details className={s.exact}><summary>Inspect & download the figures</summary><div className={s.tableActions}><span>{value.product === 'TOTAL' ? 'All products' : value.product} · separate breakdowns of the same total</span><button className={s.button} onClick={() => downloadCsv('swaps-research.csv', [...headers, 'Asset class', 'Measure', 'Source'], rows.map(r => [r.date, r.product, r.dimension, r.bucket, r.value, ASSETS[view.asset], MEASURES[view.measure], SWAPS_HOME]))}><ArrowDownToLine size={14} />Download CSV</button></div><div className={s.tableScroll}><table><caption>{ASSETS[view.asset]} · {MEASURES[view.measure]} · {unit}</caption><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{[...rows].reverse().map((r, i) => <tr key={i}><td>{r.date}</td><td>{r.product === 'TOTAL' ? 'All products' : r.product}</td><td>{r.dimension}</td><td>{r.bucket}</td><td>{r.value == null ? '—' : r.value.toLocaleString('en-US')}</td></tr>)}</tbody></table></div></details>;
}
