export const MARKET_LENSES = [
  {
    id: 'credit-banks',
    assetClass: 'Credit',
    title: 'Credit & bank balance sheets',
    description: 'Large-bank and consumer-credit filings as a proxy for deposit pressure, credit creation, capital markets activity, and loan-loss provisioning.',
    tickers: ['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'USB', 'PNC', 'TFC', 'COF', 'AXP', 'DFS', 'SCHW', 'BK'],
    kpis: ['revenueGrowth', 'netMargin', 'provisionToLoans', 'depositsToLoans', 'liabilitiesToAssets'],
    disclosureTerms: 'allowance for credit losses, nonperforming loans, deposits, liquidity, charge-offs, commercial real estate',
    pressureLanguage: 'deposit beta, credit losses, funding cost, commercial real estate exposure, loan growth',
  },
  {
    id: 'private-capital',
    assetClass: 'Private Capital',
    title: 'Private credit, asset management & market structure',
    description: 'Alternative-asset managers, exchanges, and asset managers as a lens on fundraising, private credit, market volatility, and fee-bearing asset growth.',
    tickers: ['BX', 'KKR', 'APO', 'ARES', 'BLK', 'TROW', 'ICE', 'CME', 'NDAQ', 'SCHW'],
    kpis: ['revenueGrowth', 'operatingMargin', 'netMargin', 'cashConversion', 'liabilitiesToAssets'],
    disclosureTerms: 'private credit, fee earning assets, assets under management, fundraising, market volatility, redemption',
    pressureLanguage: 'fundraising, AUM, redemption, private credit, realization activity, volatility',
  },
  {
    id: 'real-estate',
    assetClass: 'Real Assets',
    title: 'Listed real estate & digital property assets',
    description: 'REITs and listed property owners as a lens on occupancy, refinancing, rent growth, data-center demand, and rate sensitivity.',
    tickers: ['PLD', 'AMT', 'EQIX', 'DLR', 'SPG', 'O', 'PSA', 'WELL', 'VTR', 'BXP', 'ARE', 'AVB', 'EQR', 'CCI'],
    kpis: ['revenueGrowth', 'operatingMargin', 'liabilitiesToAssets', 'capexIntensity', 'assetGrowth'],
    disclosureTerms: 'occupancy, rent, tenant concentration, refinancing, interest rate risk, data center demand',
    pressureLanguage: 'lease rollover, debt maturity, occupancy, cap rate, refinancing, data center leasing',
  },
  {
    id: 'housing',
    assetClass: 'Housing',
    title: 'Housing, home improvement & building products',
    description: 'Homebuilders, home-improvement retailers, and building-products companies as a filing lens on affordability, mortgage-rate pressure, repair/remodel demand, and housing starts.',
    tickers: ['DHI', 'LEN', 'PHM', 'NVR', 'TOL', 'KBH', 'HD', 'LOW', 'BLDR', 'SHW', 'MAS', 'WHR'],
    kpis: ['revenueGrowth', 'operatingMargin', 'inventoryToSales', 'liabilitiesToAssets', 'cashConversion'],
    disclosureTerms: 'mortgage rates, housing affordability, backlog, cancellations, inventory, repair and remodel',
    pressureLanguage: 'orders, backlog, cancellation rate, affordability, mortgage rates, repair and remodel',
  },
  {
    id: 'energy-commodities',
    assetClass: 'Commodities',
    title: 'Energy, materials & commodity cash flows',
    description: 'Energy producers, services, refiners, metals and steel filings as a lens on commodity prices, capital discipline, inventory cycles, and industrial demand.',
    tickers: ['XOM', 'CVX', 'COP', 'EOG', 'OXY', 'SLB', 'HAL', 'LNG', 'PSX', 'MPC', 'FCX', 'NEM', 'NUE', 'STLD'],
    kpis: ['revenueGrowth', 'operatingMargin', 'cashConversion', 'capexIntensity', 'assetGrowth'],
    disclosureTerms: 'commodity prices, proved reserves, production, hedging, capital expenditures, steel demand, copper demand',
    pressureLanguage: 'realized prices, reserve replacement, depletion, capex discipline, refinery margins, copper demand',
  },
  {
    id: 'consumer-demand',
    assetClass: 'Consumer',
    title: 'Consumer demand, pricing & inventory',
    description: 'Retailers, restaurants, staples, and consumer brands as a filing lens on household demand, pricing power, traffic, inventory quality, and margin compression.',
    tickers: ['WMT', 'COST', 'TGT', 'HD', 'LOW', 'MCD', 'SBUX', 'NKE', 'EL', 'PG', 'KO', 'PEP', 'AMZN'],
    kpis: ['revenueGrowth', 'operatingMargin', 'netMargin', 'inventoryToSales', 'cashConversion'],
    disclosureTerms: 'inventory, markdowns, consumer demand, pricing, shrink, tariffs, traffic, average ticket',
    pressureLanguage: 'markdowns, traffic, ticket size, inventory aging, consumer pressure, shrink',
  },
  {
    id: 'ai-infrastructure',
    assetClass: 'Digital Infrastructure',
    title: 'AI infrastructure, semiconductors & hyperscale capex',
    description: 'Semiconductors, hyperscalers, cloud infrastructure, networking, and memory filings as a lens on AI infrastructure demand and capex intensity.',
    tickers: ['NVDA', 'AMD', 'AVGO', 'INTC', 'QCOM', 'MSFT', 'GOOGL', 'META', 'AMZN', 'ORCL', 'DELL', 'SMCI', 'ANET', 'MU'],
    kpis: ['revenueGrowth', 'operatingMargin', 'capexIntensity', 'rndIntensity', 'cashConversion'],
    disclosureTerms: 'artificial intelligence, data center, accelerated computing, supply constraints, capital expenditures, cloud infrastructure',
    pressureLanguage: 'data center demand, GPU supply, hyperscale capex, networking, memory demand, AI infrastructure',
  },
  {
    id: 'software-security',
    assetClass: 'Software',
    title: 'Software, cybersecurity & cloud applications',
    description: 'Enterprise software, cybersecurity, and cloud application filings as a lens on seat expansion, retention, AI monetization, and software spending.',
    tickers: ['CRM', 'NOW', 'ADBE', 'INTU', 'ADSK', 'PANW', 'CRWD', 'DDOG', 'NET', 'SNOW', 'MDB', 'TEAM', 'ZS'],
    kpis: ['revenueGrowth', 'operatingMargin', 'netMargin', 'rndIntensity', 'cashConversion'],
    disclosureTerms: 'subscription revenue, net retention, cybersecurity, artificial intelligence, customer expansion, cloud spending',
    pressureLanguage: 'renewals, customer expansion, seat growth, consumption, cloud optimization, cybersecurity demand',
  },
  {
    id: 'transport-cyclicals',
    assetClass: 'Cyclicals',
    title: 'Transport, freight & cyclical demand',
    description: 'Railroads, parcel carriers, freight brokers, and airlines as a filing lens on freight demand, fuel cost, labor pressure, travel demand, and industrial cyclicality.',
    tickers: ['UNP', 'CSX', 'NSC', 'UPS', 'FDX', 'DAL', 'UAL', 'AAL', 'LUV', 'JBHT', 'ODFL', 'CHRW'],
    kpis: ['revenueGrowth', 'operatingMargin', 'liabilitiesToAssets', 'interestBurden', 'cashConversion'],
    disclosureTerms: 'fuel prices, capacity, labor costs, freight demand, macroeconomic conditions, volume, yield',
    pressureLanguage: 'load factor, freight volume, fuel cost, wage inflation, capacity, yield',
  },
  {
    id: 'insurance',
    assetClass: 'Insurance',
    title: 'Insurance, claims & long-duration portfolios',
    description: 'Life, P&C, brokers, and insurers as a filing lens on claims severity, reserve adequacy, investment income, rate sensitivity, and catastrophe exposure.',
    tickers: ['MET', 'PRU', 'AIG', 'TRV', 'ALL', 'CB', 'PGR', 'HIG', 'AFL', 'MMC', 'AON', 'AJG'],
    kpis: ['revenueGrowth', 'netMargin', 'liabilitiesToAssets', 'interestBurden', 'cashAndInvestmentsToAssets'],
    disclosureTerms: 'investment income, unrealized losses, claims, reserves, catastrophe losses, interest rate risk',
    pressureLanguage: 'reserve development, portfolio marks, reinvestment yield, claims severity, catastrophe loss',
  },
  {
    id: 'healthcare',
    assetClass: 'Healthcare',
    title: 'Healthcare demand, managed care & therapeutics',
    description: 'Managed care, pharmaceuticals, medtech, and life-science tools as a lens on utilization, pricing, patent cycles, clinical pipelines, and healthcare demand.',
    tickers: ['UNH', 'ELV', 'HUM', 'CI', 'CVS', 'JNJ', 'PFE', 'MRK', 'ABBV', 'LLY', 'TMO', 'DHR', 'ISRG', 'BSX'],
    kpis: ['revenueGrowth', 'operatingMargin', 'netMargin', 'rndIntensity', 'cashConversion'],
    disclosureTerms: 'medical cost trend, utilization, pricing pressure, patent expiration, clinical trial, FDA approval',
    pressureLanguage: 'utilization, medical cost ratio, reimbursement, patent cliff, clinical pipeline, pricing',
  },
  {
    id: 'industrial-capex',
    assetClass: 'Industrials',
    title: 'Industrial capex, automation & equipment cycles',
    description: 'Machinery, electrical equipment, automation, engines, and rental-equipment filings as a lens on capex cycles, backlog, reshoring, and manufacturing demand.',
    tickers: ['CAT', 'DE', 'HON', 'GE', 'ETN', 'EMR', 'ITW', 'PH', 'CMI', 'MMM', 'ROK', 'URI', 'PCAR'],
    kpis: ['revenueGrowth', 'operatingMargin', 'inventoryToSales', 'capexIntensity', 'cashConversion'],
    disclosureTerms: 'backlog, orders, supply chain, automation, capital expenditures, reshoring, manufacturing demand',
    pressureLanguage: 'backlog, orders, dealer inventory, automation demand, reshoring, replacement cycle',
  },
  {
    id: 'utilities-rates',
    assetClass: 'Rates & Power',
    title: 'Utilities, power demand & rate sensitivity',
    description: 'Utilities and power infrastructure filings as a lens on regulated returns, financing cost, grid capex, electricity demand, and data-center load growth.',
    tickers: ['NEE', 'DUK', 'SO', 'AEP', 'EXC', 'SRE', 'D', 'PEG', 'ED', 'XEL', 'WEC', 'EIX'],
    kpis: ['revenueGrowth', 'operatingMargin', 'liabilitiesToAssets', 'capexIntensity', 'interestBurden'],
    disclosureTerms: 'rate case, regulatory recovery, grid modernization, transmission, power demand, data centers',
    pressureLanguage: 'rate base, regulatory recovery, grid capex, transmission, data center load, financing cost',
  },
];
