import { canonicalPortfolioCik, companyAvailable } from "./portfolioModel.js";
import { portfolioMetricState } from "./portfolioDeepResearch.js";
import { portfolioMetricDefinitionFor } from "./portfolioMetricCatalog.js";
import { portfolioPeriodKey } from "./portfolioReporting.js";

const control = (key, label, min, max, step, unit, description) => ({
  key,
  label,
  min,
  max,
  step,
  unit,
  description,
});
const REVENUE = control(
  "revenuePct",
  "Revenue change",
  -50,
  50,
  1,
  "%",
  "An assumed change from the reported period's revenue; not a market-price forecast.",
);
const COST = control(
  "costPct",
  "Operating cost change",
  -20,
  30,
  1,
  "%",
  "Changes both fixed and volume-adjusted variable operating costs after the revenue assumption.",
);
const VARIABLE = control(
  "variableCostPct",
  "Variable share of operating costs",
  0,
  100,
  5,
  "%",
  "The assumed share of implied operating costs that moves with revenue. This split is not disclosed SEC data.",
);
const OP = {
  category: "operating",
  metricLabel: "Operating income",
  ratioLabel: "Operating margin",
  ratioUnit: "%",
  impactLabel: "Operating-profit change / reported revenue (%)",
  metricDescription:
    "Reported revenue and operating income anchor a static operating-cost sensitivity.",
};
export const IMPACT_SCENARIOS = Object.freeze(
  [
    {
      id: "demand",
      label: "Demand slowdown",
      description:
        "Lower revenue tests how much profit the cost base can absorb.",
      ...OP,
      controls: [REVENUE, VARIABLE, COST],
      defaults: { revenuePct: -10, costPct: 0, variableCostPct: 40 },
    },
    {
      id: "cost",
      label: "Cost squeeze",
      description: "Higher operating costs test pricing and margin resilience.",
      ...OP,
      controls: [COST, VARIABLE, REVENUE],
      defaults: { revenuePct: 0, costPct: 5, variableCostPct: 40 },
    },
    {
      id: "combined",
      label: "Demand + cost pressure",
      description:
        "Lower revenue and higher costs compound the pressure on profit.",
      ...OP,
      controls: [REVENUE, COST, VARIABLE],
      defaults: { revenuePct: -5, costPct: 5, variableCostPct: 40 },
    },
    {
      id: "recovery",
      label: "Demand recovery",
      description:
        "Higher revenue tests the upside from a partly fixed cost base.",
      ...OP,
      controls: [REVENUE, VARIABLE, COST],
      defaults: { revenuePct: 10, costPct: 0, variableCostPct: 40 },
    },
    {
      id: "cash",
      label: "Cash-generation slowdown",
      category: "cash",
      description:
        "Less operating cash with unchanged capital spending tests the cash cushion.",
      metricLabel: "Operating cash flow less PP&E purchases",
      ratioLabel: "Operating cash flow / PP&E purchases",
      ratioUnit: "x",
      impactLabel:
        "Cash change / magnitude of reported operating cash flow (%)",
      metricDescription:
        "Cash generated by operations less reported purchases of property, plant and equipment; not a projected ending cash balance.",
      controls: [
        control(
          "cashFlowPct",
          "Operating cash flow change",
          -50,
          50,
          5,
          "%",
          "Change as a percentage of the magnitude of reported operating cash flow. A negative assumption also worsens an existing cash outflow.",
        ),
      ],
      defaults: { cashFlowPct: -20 },
    },
    {
      id: "assets",
      label: "Asset write-down",
      category: "balance",
      description:
        "A new asset loss tests how much reported shareholder equity remains.",
      metricLabel: "Shareholder equity",
      ratioLabel: "Shareholder equity / assets",
      ratioUnit: "%",
      impactLabel: "Equity change / positive reported equity (%)",
      metricDescription:
        "An incremental noncash asset loss reduces reported assets and shareholder equity equally, before taxes.",
      controls: [
        control(
          "assetLossPct",
          "New asset loss",
          0,
          20,
          0.5,
          "% of assets",
          "Applied to reported total assets and charged fully to shareholder equity, without tax benefits or use of existing allowances.",
        ),
      ],
      defaults: { assetLossPct: 2 },
    },
  ].map((item) => Object.freeze(item)),
);

const finite = (value) => typeof value === "number" && Number.isFinite(value);
const date = (value) =>
  typeof value === "string" &&
  /^\d{4}-\d{2}-\d{2}$/.test(value) &&
  Number.isFinite(Date.parse(value)) &&
  new Date(value).toISOString().slice(0, 10) === value;
const ratio = (a, b, factor = 100) =>
  b > 0 && finite((a / b) * factor) ? (a / b) * factor : null;
const median = (values) => {
  const sorted = values.filter(finite).sort((a, b) => a - b),
    n = sorted.length;
  return n
    ? n % 2
      ? sorted[(n - 1) / 2]
      : sorted[n / 2 - 1] / 2 + sorted[n / 2] / 2
    : null;
};
const strictNumber = (value) =>
  (typeof value === "number" ||
    (typeof value === "string" &&
      value.trim() &&
      /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value.trim()))) &&
  Number.isFinite(Number(value))
    ? Number(value)
    : null;

/** Validate the actual filing registrant and accession separately: filing agents can have a different accession prefix. */
function sourceValid(source, company, today) {
  if (
    !source ||
    !date(source.filed) ||
    source.filed > today ||
    !date(source.end) ||
    source.end > source.filed ||
    (source.start != null &&
      (!date(source.start) || source.start > source.end)) ||
    source.unit !== "USD" ||
    !finite(source.value) ||
    !/^[A-Za-z0-9_-]+$/.test(source.tag || "") ||
    !/^\d{10}-\d{2}-\d{6}$/.test(source.accession || "")
  )
    return false;
  try {
    const url = new URL(source.documentUrl || source.url);
    const match = url.pathname.match(
      /^\/Archives\/edgar\/data\/(\d{1,10})\/(\d{18})\/(?:[^/]+)?$/,
    );
    if (
      url.protocol !== "https:" ||
      url.username ||
      url.password ||
      url.port ||
      url.search ||
      url.hash ||
      !["sec.gov", "www.sec.gov", "data.sec.gov"].includes(url.hostname) ||
      !match ||
      match[2] !== source.accession.replaceAll("-", "")
    )
      return false;
    const cik = match[1].padStart(10, "0"),
      continuity = company.evidenceContinuity;
    const related =
      cik === company.cik ||
      (source.sourceCik === cik &&
        continuity?.currentCik === company.cik &&
        continuity?.predecessorCiks?.includes(cik) &&
        continuity?.factSourceCiks?.includes(cik));
    return related && (!source.sourceCik || source.sourceCik === cik);
  } catch {
    return false;
  }
}

const DIFFERENCE_FORMULA = "Current cumulative value − prior cumulative value";
const TTM_FORMULA = "Sum of four consecutive standalone quarters";
const nextDay = (value) =>
  new Date(Date.parse(value) + 86400000).toISOString().slice(0, 10);
const days = (start, end) =>
  (Date.parse(end) - Date.parse(start)) / 86400000 + 1;
const arithmeticEqual = (a, b, inputs = []) =>
  finite(a) &&
  finite(b) &&
  Math.abs(a - b) <=
    Math.max(1, Math.abs(a), Math.abs(b), ...inputs.map(Math.abs)) *
      Number.EPSILON *
      16;

/** Recompute the two raw-flow derivations emitted by xbrlPeriods; formula text is never evaluated as code. */
function derivedValueValid(point) {
  const { sources, observationPeriod: observation } = point;
  const formula = typeof point.formula === "string" ? point.formula : "";
  if (
    observation.kind !== "duration" ||
    ![DIFFERENCE_FORMULA, TTM_FORMULA].includes(formula) ||
    new Set(
      sources.map(
        (source) => `${source.taxonomy}|${source.tag}|${source.unit}`,
      ),
    ).size !== 1
  )
    return false;
  const differenceValid = (value, start, end) => {
    if (
      !date(start) ||
      !date(end) ||
      days(start, end) < 60 ||
      days(start, end) > 120 ||
      !finite(value)
    )
      return false;
    return sources.some(
      (current) =>
        current.end === end &&
        current.start < start &&
        days(current.start, end) > 120 &&
        days(current.start, end) <= 400 &&
        sources.some(
          (prior) =>
            prior.start === current.start &&
            nextDay(prior.end) === start &&
            prior.filed <= current.filed &&
            arithmeticEqual(current.value - prior.value, value, [
              current.value,
              prior.value,
            ]),
        ),
    );
  };
  if (formula === DIFFERENCE_FORMULA)
    return (
      point.period.kind === "quarter" &&
      differenceValid(point.value, observation.start, observation.end)
    );
  if (
    point.period.kind !== "ttm" ||
    days(observation.start, observation.end) < 300 ||
    days(observation.start, observation.end) > 400
  )
    return false;
  const intermediates = (
    Array.isArray(point.calculations) ? point.calculations : []
  ).filter((item) => item?.formula === DIFFERENCE_FORMULA);
  if (
    intermediates.some(
      (item) =>
        (item.unit && item.unit !== point.unit) ||
        !differenceValid(item.value, item.start, item.end),
    )
  )
    return false;
  const candidates = [
    ...sources.filter(
      (source) =>
        source.start &&
        days(source.start, source.end) >= 60 &&
        days(source.start, source.end) <= 120,
    ),
    ...intermediates,
  ].filter(
    (item) => item.start >= observation.start && item.end <= observation.end,
  );
  const unique = [
    ...new Map(
      candidates.map((item) => [
        `${item.start}|${item.end}|${item.value}`,
        item,
      ]),
    ).values(),
  ];
  const paths = (start, count, amounts) => {
    if (count === 4)
      return (
        start === nextDay(observation.end) &&
        arithmeticEqual(
          amounts.reduce((sum, value) => sum + value, 0),
          point.value,
          amounts,
        )
      );
    return unique.some(
      (item) =>
        item.start === start &&
        paths(nextDay(item.end), count + 1, [...amounts, item.value]),
    );
  };
  return paths(observation.start, 0, []);
}

function metric(company, key, kind, today) {
  const definition = portfolioMetricDefinitionFor(key),
    point = company?.metrics?.[key];
  if (portfolioMetricState(company, definition) !== "available")
    return {
      reason: `${definition?.label || key} is unavailable on a supported USD reporting basis.`,
    };
  if (!portfolioPeriodKey(point.period) || point.period.end > today)
    return {
      reason: `${definition.label} has an invalid or future reporting period.`,
    };
  const observation = point.observationPeriod;
  if (
    !observation ||
    observation.kind !== kind ||
    observation.end !== point.period.end ||
    (kind === "duration" && observation.start !== point.period.start) ||
    (kind === "instant" && observation.start != null)
  )
    return {
      reason: `${definition.label} does not have a compatible ${kind === "instant" ? "ending balance" : "full reporting duration"}.`,
    };
  if (
    !Array.isArray(point.sources) ||
    !point.sources.length ||
    point.sources.some((source) => !sourceValid(source, company, today))
  )
    return {
      reason: `${definition.label} lacks verified issuer filing evidence.`,
    };
  if (
    point.period.asOf &&
    (!date(point.period.asOf) ||
      point.period.asOf > today ||
      point.sources.some((source) => source.filed > point.period.asOf))
  )
    return {
      reason: `${definition.label} contains evidence outside its selected filing-date cutoff.`,
    };
  if (
    point.classification === "reported" &&
    !point.sources.some(
      (source) =>
        source.end === observation.end &&
        (source.start || null) === (observation.start || null) &&
        source.value === point.value,
    )
  )
    return {
      reason: `${definition.label} does not match its reported source value and observation dates.`,
    };
  if (point.classification !== "reported" && !derivedValueValid(point))
    return {
      reason: `${definition.label} cannot be reconciled to a supported calculation from its captured SEC inputs.`,
    };
  const calculations = [
    ...(Array.isArray(point.calculations) ? point.calculations : []),
  ];
  if (
    point.formula &&
    !calculations.some(
      (item) =>
        item?.formula === point.formula &&
        item?.value === point.value &&
        item?.start === observation.start &&
        item?.end === observation.end,
    )
  )
    calculations.push({
      formula: point.formula,
      value: point.value,
      start: observation.start,
      end: observation.end,
      unit: point.unit,
    });
  return {
    point,
    evidence: {
      key,
      label: definition.label,
      value: point.value,
      unit: point.unit,
      period: { ...point.period },
      observationPeriod: { ...observation },
      classification: point.classification,
      formula: point.formula || null,
      calculationVerification:
        point.classification === "reported"
          ? "Matches reported source value and observation dates"
          : "Recomputed from captured SEC inputs",
      calculations,
      sources: point.sources.map((source) => {
        const url = source.documentUrl || source.url,
          index = new URL(url).pathname.endsWith("/");
        return {
          ...source,
          url,
          linkKind: index ? "filing-index" : "filing-document",
          linkLabel: index ? "SEC filing index" : "SEC filing",
        };
      }),
    },
  };
}

function calculate(category, values, inputs) {
  if (category === "operating") {
    const [revenue, income] = values,
      costs = revenue - income,
      g = inputs.revenuePct / 100,
      v = inputs.variableCostPct / 100,
      c = inputs.costPct / 100;
    if (!(revenue > 0) || !(costs >= 0) || !finite(costs))
      return {
        reason:
          "The operating model requires positive revenue and nonnegative implied operating costs.",
      };
    const modeledRevenue = revenue * (1 + g),
      volumeCosts = costs * (1 + v * g);
    if (![modeledRevenue, volumeCosts, volumeCosts * (1 + c)].every(finite))
      return {
        reason:
          "These operating assumptions exceed the supported numerical range.",
      };
    const components = [
      { id: "revenue", label: "Revenue change", value: revenue * g },
      {
        id: "volumeCosts",
        label: "Volume-linked cost change",
        value: -costs * v * g,
      },
      {
        id: "costChange",
        label: "Operating cost change",
        value: -volumeCosts * c,
      },
    ];
    const change = components.reduce((sum, item) => sum + item.value, 0),
      modeled = income + change;
    return {
      baseline: income,
      modeled,
      change,
      impactPct: ratio(change, revenue),
      beforeRatio: ratio(income, revenue),
      afterRatio: ratio(modeled, modeledRevenue),
      components,
      modeledRevenue,
      modeledCosts: volumeCosts * (1 + c),
      baselineCosts: costs,
    };
  }
  if (category === "cash") {
    const [ocf, capex] = values;
    if (!ocf || capex < 0)
      return {
        reason:
          "The cash sensitivity requires nonzero operating cash flow and nonnegative reported PP&E purchases.",
      };
    const change = (Math.abs(ocf) * inputs.cashFlowPct) / 100,
      baseline = ocf - capex,
      modeledOcf = ocf + change;
    return {
      baseline,
      modeled: baseline + change,
      change,
      impactPct: ratio(change, Math.abs(ocf)),
      beforeRatio: ratio(ocf, capex, 1),
      afterRatio: ratio(modeledOcf, capex, 1),
      components: [
        { id: "cashFlow", label: "Operating cash flow change", value: change },
      ],
      modeledCashFlow: modeledOcf,
      capex,
    };
  }
  const [assets, equity, cash] = values;
  if (!(assets > 0) || (finite(cash) && (cash < 0 || cash > assets)))
    return {
      reason:
        "The balance sensitivity requires positive assets and compatible nonnegative cash no greater than assets.",
    };
  const loss = (assets * inputs.assetLossPct) / 100;
  if (
    finite(cash) &&
    loss > assets - cash + Math.max(assets, cash) * Number.EPSILON * 16
  )
    return {
      reason:
        "The assumed noncash asset loss exceeds reported assets less cash.",
    };
  const modeledAssets = assets - loss;
  if (!(modeledAssets > 0))
    return { reason: "The assumed loss leaves no positive asset base." };
  return {
    baseline: equity,
    modeled: equity - loss,
    change: -loss,
    impactPct: ratio(-loss, equity),
    beforeRatio: ratio(equity, assets),
    afterRatio: ratio(equity - loss, modeledAssets),
    components: [
      { id: "assetLoss", label: "New noncash asset loss", value: -loss },
    ],
    modeledAssets,
    noncashCapacityVerified: finite(cash),
  };
}

const methodNotes = {
  operating: [
    "Implied operating costs = reported revenue − operating income. The user-assumed variable share moves in proportion to revenue; the remainder stays fixed. The cost-change assumption is applied afterward to both parts.",
    "Operating profit change / reported revenue compares the dollar effect with the original revenue base. It is not a stock return or the change in operating margin.",
    "No tax, financing, balance-sheet, cash-flow, volume/price decomposition, or management response is modeled.",
  ],
  cash: [
    "Modeled operating cash flow = reported operating cash flow + its absolute magnitude × the assumed change. PP&E purchases remain unchanged. A negative assumption worsens an existing operating cash outflow.",
    "Operating cash flow less PP&E purchases is a limited cash-generation measure, not a forecast of ending cash or a complete measure of distributable cash. No new financing, dividends, repurchases, acquisitions, or working-capital response is modeled.",
    "Coverage ratio = operating cash flow / PP&E purchases. It is undefined when PP&E purchases are zero.",
  ],
  balance: [
    "A new noncash loss equals the assumed percentage of reported total assets. Reported assets and shareholder equity decline by the same dollar amount; no tax benefit or use of existing allowances is assumed.",
    "Shareholder equity / assets is an accounting ratio, not a regulatory capital ratio or a probability of default. Consolidated assets and shareholder equity may have different scopes.",
    "Equity change as a percentage is unavailable when reported shareholder equity is zero or negative. The dollar and accounting-ratio sensitivities remain visible.",
  ],
};

/** Company sensitivities are independent of allocation. Weights annotate coverage only when complete and reviewed. */
export function buildPortfolioImpactScenarios(report, companies, options = {}) {
  const scenario =
    IMPACT_SCENARIOS.find(
      (item) => item.id === (options.scenarioId || "demand"),
    ) || IMPACT_SCENARIOS[0];
  const errors = [],
    inputs = {};
  if (
    options.scenarioId &&
    !IMPACT_SCENARIOS.some((item) => item.id === options.scenarioId)
  )
    errors.push("Choose an available scenario.");
  for (const item of scenario.controls) {
    const value =
      options[item.key] === undefined
        ? scenario.defaults[item.key]
        : strictNumber(options[item.key]);
    if (value === null || value < item.min || value > item.max)
      errors.push(
        `${item.label} must be a number from ${item.min} to ${item.max}.`,
      );
    inputs[item.key] = value;
  }
  const now = options.now ?? Date.now(),
    time = new Date(now).getTime();
  const today = finite(time) ? new Date(time).toISOString().slice(0, 10) : null;
  if (!today) errors.push("The calculation date is invalid.");
  const scope = options.scope || "all",
    targetCik = canonicalPortfolioCik(options.targetCik),
    targetSector =
      typeof options.targetSector === "string" ? options.targetSector : "";
  if (!["all", "company", "sector"].includes(scope))
    errors.push("Choose all companies, one company, or one sector.");
  const byCik = new Map(),
    ambiguous = new Set();
  for (const company of Array.isArray(companies) ? companies : []) {
    const cik = canonicalPortfolioCik(company?.cik);
    if (!cik) continue;
    if (byCik.has(cik)) ambiguous.add(cik);
    else byCik.set(cik, company);
  }
  const issuers = [
    ...new Map(
      (report?.concentration?.issuers || [])
        .filter((item) => canonicalPortfolioCik(item.cik))
        .map((item) => [
          canonicalPortfolioCik(item.cik),
          {
            ...item,
            cik: canonicalPortfolioCik(item.cik),
            sector: item.sector || "Unclassified",
          },
        ]),
    ).values(),
  ];
  if (scope === "company" && !issuers.some((item) => item.cik === targetCik))
    errors.push("Choose a company in this research list.");
  if (
    scope === "sector" &&
    (!targetSector || !issuers.some((item) => item.sector === targetSector))
  )
    errors.push("Choose a sector in this research list.");
  const selected = issuers.filter((item) =>
    scope === "company"
      ? item.cik === targetCik
      : scope === "sector"
        ? item.sector === targetSector
        : true,
  );
  const weighted =
    report?.weighted === true &&
    report?.concentration?.complete === true &&
    !(report?.unresolvedCount > 0) &&
    issuers.every(
      (item) =>
        item.weightComplete && finite(item.weightPct) && item.weightPct >= 0,
    ) &&
    Math.abs(issuers.reduce((sum, item) => sum + item.weightPct, 0) - 100) <=
      1e-6;
  const exclusions = [],
    rows = [];
  let eligibleCount = 0;
  for (const issuer of selected) {
    const company = byCik.get(issuer.cik),
      identity = {
        cik: issuer.cik,
        rowId: issuer.rowIds?.[0] || "",
        name: issuer.name || company?.name || issuer.cik,
        ticker: (issuer.tickers || []).join(" / ") || company?.ticker || "",
        sector: issuer.sector || "Unclassified",
        weightPct: weighted ? issuer.weightPct : null,
      };
    const applicable =
      issuer.kind !== "fund" &&
      (scenario.category === "balance" || company?.lens === "corporate");
    const exclude = (reason, code = "evidence") =>
      exclusions.push({ ...identity, reason, code, applicable });
    if (!applicable) {
      exclude(
        issuer.kind === "fund"
          ? "Fund look-through financials are not modeled."
          : "This operating-company sensitivity does not apply to financial institutions or an unclassified business model.",
        "not-applicable",
      );
      continue;
    }
    eligibleCount++;
    if (errors.length) {
      exclude(
        "Complete valid scenario inputs to calculate this company.",
        "inputs",
      );
      continue;
    }
    if (ambiguous.has(issuer.cik)) {
      exclude(
        "Conflicting company snapshots share this issuer identity.",
        "identity",
      );
      continue;
    }
    if (!companyAvailable(company)) {
      exclude("Supported captured company financial evidence is unavailable.");
      continue;
    }
    const keys =
      scenario.category === "operating"
        ? ["revenue", "operatingIncome"]
        : scenario.category === "cash"
          ? ["operatingCashFlow", "capex"]
          : ["totalAssets", "stockholdersEquity"];
    const kind = scenario.category === "balance" ? "instant" : "duration";
    const checked = keys.map((key) => metric(company, key, kind, today));
    if (checked.some((item) => item.reason)) {
      exclude(checked.find((item) => item.reason).reason);
      continue;
    }
    if (
      new Set(checked.map((item) => portfolioPeriodKey(item.point.period)))
        .size !== 1
    ) {
      exclude(
        "Financial inputs have different full reporting periods.",
        "period",
      );
      continue;
    }
    const evidence = checked.map((item) => item.evidence),
      values = checked.map((item) => item.point.value);
    if (scenario.category === "balance") {
      const cash = metric(company, "cash", "instant", today);
      if (
        !cash.reason &&
        portfolioPeriodKey(cash.point.period) ===
          portfolioPeriodKey(checked[0].point.period)
      ) {
        values.push(cash.point.value);
        evidence.push(cash.evidence);
      }
    }
    const result = calculate(scenario.category, values, inputs);
    if (
      result.reason ||
      ![
        result.baseline,
        result.modeled,
        result.change,
        ...result.components.map((item) => item.value),
      ].every(finite)
    ) {
      exclude(
        result.reason || "These values exceed the supported numerical range.",
        "model",
      );
      continue;
    }
    const primary = scenario.controls[0],
      span =
        primary.key === "assetLossPct" ? 2 : primary.key === "costPct" ? 5 : 10;
    const shocks = [
      ...new Set([
        primary.min,
        ...[-2, -1, 0, 1, 2].map((n) =>
          Math.max(
            primary.min,
            Math.min(primary.max, inputs[primary.key] + span * n),
          ),
        ),
        primary.max,
      ]),
    ].sort((a, b) => a - b);
    const sensitivity = shocks.map((shock) => {
      const value = calculate(scenario.category, values, {
        ...inputs,
        [primary.key]: shock,
      });
      return {
        shock,
        value: value.reason || !finite(value.modeled) ? null : value.modeled,
        ratio: value.reason ? null : value.afterRatio,
        impactPct: value.reason ? null : value.impactPct,
        reason: value.reason || null,
      };
    });
    rows.push({
      ...identity,
      ...result,
      unit: "USD",
      period: { ...checked[0].point.period },
      metricLabel: scenario.metricLabel,
      ratioLabel: scenario.ratioLabel,
      ratioUnit: scenario.ratioUnit,
      impactLabel: scenario.impactLabel,
      ratioChange:
        finite(result.beforeRatio) && finite(result.afterRatio)
          ? result.afterRatio - result.beforeRatio
          : null,
      enteredLoss: result.baseline >= 0 && result.modeled < 0,
      alreadyNegative: result.baseline < 0,
      recovered: result.baseline < 0 && result.modeled >= 0,
      evidence,
      sensitivity,
      sensitivityLabel: primary.label,
      sensitivityUnit: primary.unit,
      stale: company.status === "stale" || company.cache?.status === "stale",
      notes:
        scenario.category === "balance" && !result.noncashCapacityVerified
          ? [
              "Compatible reported cash is unavailable; the noncash asset-loss ceiling cannot be verified.",
            ]
          : [],
    });
  }
  rows.sort(
    (a, b) =>
      (a.afterRatio ?? Infinity) - (b.afterRatio ?? Infinity) ||
      a.ticker.localeCompare(b.ticker),
  );
  const sumWeight = (collection) =>
    weighted ? collection.reduce((sum, item) => sum + item.weightPct, 0) : null;
  return {
    scenario,
    inputs,
    errors,
    rows,
    exclusions,
    coverage: {
      includedCount: selected.length,
      eligibleCount,
      modeledCount: rows.length,
      excludedCount: exclusions.length,
      unavailableCount: exclusions.filter((item) => item.applicable).length,
      notApplicableCount: exclusions.filter((item) => !item.applicable).length,
      unresolvedCount: report?.unresolvedCount || 0,
      weighted,
      coveredWeightPct: sumWeight(rows),
      excludedWeightPct: sumWeight(exclusions),
      allocationLabel: weighted
        ? report.label || "Reviewed allocation"
        : "Company counts; weights not required",
    },
    summary: {
      medianImpactPct: median(rows.map((row) => row.impactPct)),
      medianBeforeRatio: median(rows.map((row) => row.beforeRatio)),
      medianAfterRatio: median(rows.map((row) => row.afterRatio)),
      enteredLossCount: rows.filter((row) => row.enteredLoss).length,
      alreadyNegativeCount: rows.filter((row) => row.alreadyNegative).length,
      negativeAfterCount: rows.filter((row) => row.modeled < 0).length,
      recoveredCount: rows.filter((row) => row.recovered).length,
      impactMeasuredCount: rows.filter((row) => finite(row.impactPct)).length,
      ratioMeasuredCount: rows.filter((row) => finite(row.afterRatio)).length,
      enteredLossWeightPct: sumWeight(rows.filter((row) => row.enteredLoss)),
      periodCount: new Set(rows.map((row) => portfolioPeriodKey(row.period)))
        .size,
    },
    assumptions: [
      "Illustrative, editable assumptions applied independently to each company's captured SEC financial baseline. Not a forecast, historical stress test, stock-price return, or probability estimate.",
      "Company results and company-count summaries do not require portfolio weights. Reviewed, complete investment weights annotate coverage only; company dollar impacts are never summed as portfolio profit or loss.",
      ...methodNotes[scenario.category],
      "Each company uses its own full reporting period. The median summarizes the available companies, which may have different fiscal calendars; it is not a synchronized or weighted portfolio result.",
      "CFTC market-wide positioning can motivate research into a filing-linked market. It does not set these assumptions or establish a company's hedge, price sensitivity, or earnings response.",
    ],
  };
}
