/** Shared Analysis metric definitions. Values and evidence always come from each captured issuer. */
export const PORTFOLIO_METRIC_CATALOG = [
  {
    key: "revenue",
    label: "Revenue",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "costOfRevenue",
    label: "Cost of Revenue",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "grossProfit",
    label: "Gross Profit",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "rnd",
    label: "R&D Expense",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "sga",
    label: "SG&A Expense",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "operatingIncome",
    label: "Operating Income",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "interestExpense",
    label: "Interest Expense",
    format: "currency",
    category: "income",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "pretaxIncome",
    label: "Pre-tax Income",
    format: "currency",
    category: "income",
    order: 2,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "incomeTax",
    label: "Income Tax",
    format: "currency",
    category: "income",
    order: 3,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "netIncome",
    label: "Net Income",
    format: "currency",
    category: "income",
    order: 4,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "epsBasic",
    label: "EPS (Basic)",
    format: "eps",
    category: "income",
    order: 5,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "epsDiluted",
    label: "EPS (Diluted)",
    format: "eps",
    category: "income",
    order: 6,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "sharesDiluted",
    label: "Diluted Shares",
    format: "shares",
    category: "income",
    order: 7,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cash",
    label: "Cash & Equivalents",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "shortTermInvestments",
    label: "Short-term Investments",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "receivables",
    label: "Accounts Receivable",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "inventory",
    label: "Inventory",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "currentAssets",
    label: "Total Current Assets",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "ppe",
    label: "Property, Plant & Equipment",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "goodwill",
    label: "Goodwill",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "intangibles",
    label: "Intangible Assets",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "totalAssets",
    label: "Total Assets",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "accountsPayable",
    label: "Accounts Payable",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "shortTermDebt",
    label: "Short-term Debt",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "currentLiabilities",
    label: "Total Current Liabilities",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "longTermDebt",
    label: "Long-term Debt",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "totalLiabilities",
    label: "Total Liabilities",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "retainedEarnings",
    label: "Retained Earnings",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "stockholdersEquity",
    label: "Stockholders' Equity",
    format: "currency",
    category: "balance",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "operatingCashFlow",
    label: "Operating Cash Flow",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "investingCashFlow",
    label: "Investing Cash Flow",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "financingCashFlow",
    label: "Financing Cash Flow",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "capex",
    label: "Capital Expenditures",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "dividendsPaid",
    label: "Dividends Paid",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "stockRepurchased",
    label: "Stock Repurchased",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "debtIssued",
    label: "Debt Issued",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "debtRepaid",
    label: "Debt Repaid",
    format: "currency",
    category: "cashflow",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "roe",
    label: "Return on average equity",
    format: "percent",
    category: "ratios",
    formula:
      "Net income / average beginning and ending equity × annualization factor × 100",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "roa",
    label: "Return on average assets",
    format: "percent",
    category: "ratios",
    formula:
      "Net income / average beginning and ending assets × annualization factor × 100",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "equityAssets",
    label: "Equity / assets",
    format: "percent",
    category: "ratios",
    formula: "Equity / total assets × 100",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "operatingMargin",
    label: "Operating margin",
    format: "percent",
    category: "ratios",
    formula: "Operating income / revenue × 100",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "netMargin",
    label: "Net margin",
    format: "percent",
    category: "ratios",
    formula: "Net income / revenue × 100",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "freeCashFlow",
    label: "Operating cash flow less PP&E purchases",
    format: "currency",
    category: "cashflow",
    formula:
      "Operating cash flow − purchases of property, plant and equipment; limited usefulness for financial institutions",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashAssets",
    label: "Cash / assets",
    format: "percent",
    category: "ratios",
    formula: "Reported cash / total assets × 100",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "currentRatio",
    label: "Current ratio",
    format: "decimal",
    category: "ratios",
    formula: "Current assets / current liabilities",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "debtAssets",
    label: "Reported debt / assets",
    format: "percent",
    category: "ratios",
    formula:
      "(Reported current debt + noncurrent debt) / assets × 100; both debt components required",
    order: 100,
    lenses: ["corporate", "insurance"],
  },
  {
    key: "liabilitiesAndEquity",
    label: "Reported liabilities and equity",
    format: "currency",
    category: "checks",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashFlowChange",
    label: "Reported change in cash, including FX",
    format: "currency",
    category: "checks",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "fxCash",
    label: "Effect of exchange rates on cash",
    format: "currency",
    category: "checks",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "openingReceivables",
    label: "Opening receivables",
    format: "currency",
    category: "workingCapitalInputs",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "openingInventory",
    label: "Opening inventory",
    format: "currency",
    category: "workingCapitalInputs",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "openingAccountsPayable",
    label: "Opening accounts payable",
    format: "currency",
    category: "workingCapitalInputs",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "grossMargin",
    label: "Gross margin",
    format: "percent",
    category: "ratios",
    formula: "Reported gross profit / revenue × 100",
    order: 100,
    lenses: ["corporate"],
  },
  {
    key: "cashConversion",
    label: "Operating cash flow / net income",
    format: "percent",
    category: "ratios",
    formula: "Operating cash flow / positive net income × 100",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashAdjustments",
    label: "Noncash items and working capital, net",
    format: "currency",
    category: "cashflow",
    formula:
      "Operating cash flow − net income; residual, not an attribution to individual causes",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashReturned",
    label: "Dividends + common share repurchases",
    format: "currency",
    category: "cashflow",
    formula:
      "Reported dividends + common share repurchases; both components required",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashAfterReturns",
    label: "Cash after PP&E and shareholder returns",
    format: "currency",
    category: "cashflow",
    formula:
      "Operating cash flow − PP&E purchases − dividends − common share repurchases; excludes other investing and financing flows",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "netLongTermDebt",
    label: "Net long-term debt issuance",
    format: "currency",
    category: "cashflow",
    formula:
      "Reported long-term debt proceeds − repayments; both components required",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "balanceResidual",
    label: "Balance equation residual",
    format: "currency",
    category: "checks",
    formula: "Assets − reported liabilities and stockholders’ equity",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "cashFlowResidual",
    label: "Cash-flow reconciliation residual",
    format: "currency",
    category: "checks",
    formula:
      "Operating + investing + financing cash flow + FX − reported cash change",
    order: 100,
    lenses: ["corporate", "banking", "insurance"],
  },
  {
    key: "averageAssets",
    label: "Average assets",
    format: "currency",
    category: "drivers",
    order: 100,
    lenses: ["corporate", "banking"],
  },
  {
    key: "averageEquity",
    label: "Average equity",
    format: "currency",
    category: "drivers",
    order: 100,
    lenses: ["corporate", "banking"],
  },
  {
    key: "assetTurnover",
    label: "Revenue / average assets, annualized",
    format: "decimal",
    category: "drivers",
    order: 100,
    lenses: ["corporate", "banking"],
  },
  {
    key: "equityMultiplier",
    label: "Average assets / average equity",
    format: "decimal",
    category: "drivers",
    formula: "Average assets / positive average equity",
    order: 100,
    lenses: ["corporate", "banking"],
  },
  {
    key: "dupontRoe",
    label: "ROE explained by three drivers",
    format: "percent",
    category: "drivers",
    formula:
      "Net margin (%) × annualized revenue / average assets × average assets / average equity",
    order: 100,
    lenses: ["corporate", "banking"],
  },
  {
    key: "bankRevenue",
    label: "Net interest + noninterest income",
    format: "currency",
    category: "income",
    formula: "Net interest income before provision + noninterest income",
    order: 0,
    lenses: ["banking"],
  },
  {
    key: "netInterestIncome",
    label: "Net interest income",
    format: "currency",
    category: "income",
    order: 1,
    lenses: ["banking"],
  },
  {
    key: "noninterestIncome",
    label: "Noninterest income",
    format: "currency",
    category: "income",
    order: 2,
    lenses: ["banking"],
  },
  {
    key: "provisionForLoanLoss",
    label: "Provision for credit losses",
    format: "currency",
    category: "income",
    order: 3,
    lenses: ["banking"],
  },
  {
    key: "noninterestExpense",
    label: "Noninterest expense",
    format: "currency",
    category: "income",
    order: 4,
    lenses: ["banking"],
  },
  {
    key: "loans",
    label: "Reported net loans",
    format: "currency",
    category: "balance",
    order: 14,
    lenses: ["banking"],
  },
  {
    key: "allowanceForLoanLoss",
    label: "Allowance for credit losses",
    format: "currency",
    category: "balance",
    order: 15,
    lenses: ["banking"],
  },
  {
    key: "deposits",
    label: "Deposits",
    format: "currency",
    category: "balance",
    order: 17,
    lenses: ["banking"],
  },
  {
    key: "loanDeposits",
    label: "Net loans / deposits",
    format: "percent",
    category: "ratios",
    formula: "Reported net loans / deposits × 100",
    order: 100,
    lenses: ["banking"],
  },
  {
    key: "allowanceLoans",
    label: "Allowance / net loans",
    format: "percent",
    category: "ratios",
    formula: "Reported allowance for credit losses / net loans × 100",
    order: 100,
    lenses: ["banking"],
  },
  {
    key: "provisionLoans",
    label: "Provision / net loans",
    format: "percent",
    category: "ratios",
    formula:
      "Credit loss provision / ending net loans × annualization factor × 100",
    order: 100,
    lenses: ["banking"],
  },
  {
    key: "efficiency",
    label: "Efficiency ratio",
    format: "percent",
    category: "ratios",
    formula:
      "Noninterest expense / (net interest income before provision + noninterest income) × 100",
    order: 100,
    lenses: ["banking"],
  },
  {
    key: "bankNetMargin",
    label: "Net income / bank revenue",
    format: "percent",
    category: "ratios",
    formula:
      "Net income / (net interest income before provision + noninterest income) × 100",
    order: 100,
    lenses: ["banking"],
  },
  {
    key: "premiumsEarned",
    label: "Net premiums earned",
    format: "currency",
    category: "income",
    order: 0,
    lenses: ["insurance"],
  },
  {
    key: "investmentIncome",
    label: "Investment income",
    format: "currency",
    category: "income",
    order: 1,
    lenses: ["insurance"],
  },
  {
    key: "revenueGrowth",
    label: "Revenue growth",
    format: "percent",
    category: "ratios",
    lenses: ["corporate"],
  },
  {
    key: "debt",
    label: "Reported debt",
    format: "currency",
    category: "balance",
    lenses: ["corporate", "insurance"],
  },
];
export const portfolioMetricDefinitionFor = (key) =>
  PORTFOLIO_METRIC_CATALOG.find((d) => d.key === key);
