"use client";

import { useId, useMemo, useState, type KeyboardEvent } from "react";
import {
  ArrowDown,
  ArrowUp,
  Download,
  ExternalLink,
  FileSearch,
  Plus,
  RotateCcw,
  Search,
  SlidersHorizontal,
  X,
} from "lucide-react";
import {
  availablePortfolioScreenMetrics,
  buildPortfolioScreen,
  portfolioScreenCsv,
  PORTFOLIO_SCREEN_PRESETS,
  PORTFOLIO_SECTOR_UNCOVERED,
} from "../../../utils/portfolioScreening.js";
import { downloadText } from "../../../utils/download.js";
import CompanyResearchTable from "./CompanyResearchTable";
import styles from "./PortfolioScreener.module.css";

type Rule = { metricId: string; min: string; max: string };
type Props = {
  report: any;
  companies?: any[];
  onDisclosure?: (query: string, ciks: string[]) => void;
  onInspectCompany: (rowId: string) => void;
};
type TableView = {
  id: string;
  label: string;
  description: string;
  columns: string[];
};

const EMPTY_COMPANIES: any[] = [];
const LENS_LABELS: Record<string, string> = {
  corporate: "Operating companies",
  banking: "Banks",
  insurance: "Insurers",
  common: "Common financials",
  unknown: "Unclassified",
};
const CATEGORY_LABELS: Record<string, string> = {
  income: "Income statement",
  balance: "Balance sheet",
  cashflow: "Cash flow",
  ratios: "Ratios & returns",
  drivers: "Returns & efficiency",
  workingCapitalInputs: "Working-capital inputs",
  checks: "Evidence checks",
};
const TABLE_VIEWS: TableView[] = [
  {
    id: "overview",
    label: "Overview",
    description: "Comparable growth, returns and balance-sheet measures.",
    columns: [
      "revenueGrowth",
      "operatingMargin",
      "roe",
      "roa",
      "equityAssets",
      "freeCashFlowMargin",
    ],
  },
  {
    id: "growth",
    label: "Growth",
    description: "Reported growth, earnings and reinvestment measures.",
    columns: [
      "revenueGrowth",
      "revenue",
      "operatingIncome",
      "epsDiluted",
      "rnd",
      "capex",
    ],
  },
  {
    id: "profitability",
    label: "Profitability",
    description: "Margins and returns generated by assets and equity.",
    columns: [
      "grossMargin",
      "operatingMargin",
      "pretaxMargin",
      "netMargin",
      "roe",
      "roa",
    ],
  },
  {
    id: "cash-flow",
    label: "Cash flow",
    description: "Cash generation, investment and shareholder distributions.",
    columns: [
      "operatingCashFlow",
      "freeCashFlow",
      "cashConversion",
      "freeCashFlowMargin",
      "cashAfterReturns",
      "cashReturned",
    ],
  },
  {
    id: "liquidity-leverage",
    label: "Liquidity & leverage",
    description: "Near-term liquidity and balance-sheet funding measures.",
    columns: [
      "currentRatio",
      "cashRatio",
      "cashAssets",
      "debtAssets",
      "liabilitiesAssets",
      "operatingInterestCoverage",
    ],
  },
  {
    id: "income-statement",
    label: "Income statement",
    description: "Reported revenue and earnings across compatible financial sets.",
    columns: [
      "revenue",
      "bankRevenue",
      "premiumsEarned",
      "operatingIncome",
      "pretaxIncome",
      "netIncome",
    ],
  },
  {
    id: "balance-sheet",
    label: "Balance sheet",
    description: "Point-in-time assets, obligations and reported capital.",
    columns: [
      "cash",
      "totalAssets",
      "debt",
      "totalLiabilities",
      "stockholdersEquity",
      "deposits",
    ],
  },
  {
    id: "per-share",
    label: "Per share",
    description: "Reported earnings per share and diluted share counts.",
    columns: ["epsBasic", "epsDiluted", "sharesDiluted"],
  },
  {
    id: "banking",
    label: "Banking",
    description: "Bank funding, lending, efficiency and return measures.",
    columns: [
      "netInterestIncome",
      "loans",
      "deposits",
      "loanDeposits",
      "efficiency",
      "bankNetMargin",
    ],
  },
  {
    id: "insurance",
    label: "Insurance",
    description: "Premiums, investment income, earnings and capital.",
    columns: [
      "premiumsEarned",
      "investmentIncome",
      "netIncome",
      "totalAssets",
      "stockholdersEquity",
      "roe",
    ],
  },
];

const finite = (value: unknown): value is number =>
  typeof value === "number" && Number.isFinite(value);
const compactNumber = (value: number, digits = 2) =>
  value.toLocaleString("en-US", {
    notation: Math.abs(value) >= 10_000 ? "compact" : "standard",
    maximumFractionDigits: digits,
  });
const formatValue = (value: unknown, unit = "") => {
  if (!finite(value)) return "—";
  if (unit === "USD")
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      notation: "compact",
      maximumFractionDigits: 2,
    }).format(value);
  if (unit === "%") return `${compactNumber(value)}%`;
  if (unit === "USD/shares") return `$${compactNumber(value, 3)}`;
  if (unit === "shares") return compactNumber(value);
  if (unit === "x") return `${compactNumber(value, 2)}×`;
  return `${compactNumber(value)}${unit ? ` ${unit}` : ""}`;
};
const formatDate = (value: string | null | undefined) =>
  value
    ? new Date(`${value}T00:00:00Z`).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
        timeZone: "UTC",
      })
    : "Period unavailable";
const periodLabel = (cell: any, category?: string) => {
  if (!cell?.periodEnd) return "Period unavailable";
  if (category === "balance") return `As of ${formatDate(cell.periodEnd)}`;
  const kind = String(cell.periodKey || "").split("|")[0];
  const year = cell.periodEnd.slice(0, 4);
  if (kind === "annual") return `FY ${year}`;
  if (kind === "quarter") return `Quarter ${year}`;
  if (kind === "ytd") return `YTD ${year}`;
  if (kind === "ttm") return `TTM ${year}`;
  return `Ended ${formatDate(cell.periodEnd)}`;
};
const ruleBound = (value: string, unit: string) => {
  const parsed = Number(value);
  return value.trim() && Number.isFinite(parsed)
    ? formatValue(parsed, unit)
    : value.trim();
};
const ruleLabel = (rule: Rule, metric: any) => {
  const label = metric?.label || "Unsupported measure";
  if (rule.min.trim() && rule.max.trim())
    return `${label}: ${ruleBound(rule.min, metric?.unit)}–${ruleBound(rule.max, metric?.unit)}`;
  if (rule.min.trim())
    return `${label} ≥ ${ruleBound(rule.min, metric?.unit)}`;
  if (rule.max.trim())
    return `${label} ≤ ${ruleBound(rule.max, metric?.unit)}`;
  return `${label}: add a bound`;
};
const percent = (value: unknown) =>
  finite(value) ? `${compactNumber(value, 1)}%` : "—";

export default function PortfolioScreener({
  report,
  onDisclosure,
  companies = EMPTY_COMPANIES,
  onInspectCompany,
}: Props) {
  const id = useId();
  const [rules, setRules] = useState<Rule[]>(() =>
    PORTFOLIO_SCREEN_PRESETS[0].rules.map((rule) => ({ ...rule })),
  );
  const [lens, setLens] = useState("");
  const [matchingPeriodOnly, setMatchingPeriodOnly] = useState(true);
  const [disclosureQuery, setDisclosureQuery] = useState("liquidity");
  const [industry, setIndustry] = useState("");
  const [sector, setSector] = useState("");
  const [sortBy, setSortBy] = useState("name");
  const [direction, setDirection] = useState("asc");
  const [companyQuery, setCompanyQuery] = useState("");
  const [view, setView] = useState("overview");
  const [rulesOpen, setRulesOpen] = useState(false);
  const [disclosuresOpen, setDisclosuresOpen] = useState(false);
  const [downloadMessage, setDownloadMessage] = useState("");

  const availableMetrics = useMemo(
    () =>
      availablePortfolioScreenMetrics(report, companies, {
        sector,
        industry,
        lens,
        matchingPeriodOnly: report.fullPeriodEvidence && matchingPeriodOnly,
      }),
    [report, companies, sector, industry, lens, matchingPeriodOnly],
  );
  const availableMetricIds = useMemo(
    () => new Set(availableMetrics.map((metric: any) => metric.id)),
    [availableMetrics],
  );
  const metricById = useMemo(
    () =>
      new Map<string, any>(
        report.metrics.map((metric: any) => [metric.id, metric]),
      ),
    [report.metrics],
  );
  const unavailableRules = rules.filter(
    (rule) => !availableMetricIds.has(rule.metricId),
  );
  const availableViews = TABLE_VIEWS.map((item) => ({
    ...item,
    columns: item.columns.filter((metricId) =>
      availableMetricIds.has(metricId),
    ),
  })).filter((item) => item.id === "overview" || item.columns.length > 0);
  const activeView =
    availableViews.find((item) => item.id === view) || availableViews[0];
  const displayMetricIds = [
    ...new Set([
      ...rules.map((rule) => rule.metricId),
      ...activeView.columns,
    ]),
  ];
  const displayMetrics = displayMetricIds
    .map((metricId) => metricById.get(metricId))
    .filter(Boolean) as any[];
  const ruleMetricIds = new Set(rules.map((rule) => rule.metricId));
  const effectiveSort =
    sortBy === "name" ||
    (sortBy === "weight" && report.weighted) ||
    displayMetricIds.includes(sortBy)
      ? sortBy
      : "name";
  const result = buildPortfolioScreen(report, companies, rules, {
    sector,
    industry,
    lens,
    matchingPeriodOnly: report.fullPeriodEvidence && matchingPeriodOnly,
    displayMetricIds,
    sortBy: effectiveSort,
    direction,
  });
  const presets = PORTFOLIO_SCREEN_PRESETS.filter(
    (preset) =>
      preset.rules.every((rule) => availableMetricIds.has(rule.metricId)) &&
      (buildPortfolioScreen(report, companies, preset.rules, {
        sector,
        industry,
        lens,
        matchingPeriodOnly: report.fullPeriodEvidence && matchingPeriodOnly,
      })?.measuredCount || 0) > 0,
  );
  const metricGroups = useMemo(() => {
    const groups = new Map<string, any[]>();
    for (const metric of availableMetrics) {
      const label = CATEGORY_LABELS[metric.category] || "Other measures";
      groups.set(label, [...(groups.get(label) || []), metric]);
    }
    return [...groups.entries()];
  }, [availableMetrics]);
  const lensCounts = useMemo(() => {
    const counts = new Map<string, number>();
    for (const company of companies) {
      const key = company?.lens || "unknown";
      counts.set(key, (counts.get(key) || 0) + 1);
    }
    return counts;
  }, [companies]);
  const normalizedQuery = companyQuery.trim().toLowerCase();
  const visibleMatches = result.matches.filter((row: any) =>
    !normalizedQuery
      ? true
      : [row.name, row.cik, ...(row.tickers || [])]
          .join(" ")
          .toLowerCase()
          .includes(normalizedQuery),
  );

  function changeRule(index: number, patch: Partial<Rule>) {
    setRules((current) =>
      current.map((rule, itemIndex) =>
        itemIndex === index ? { ...rule, ...patch } : rule,
      ),
    );
    setSortBy("name");
    setDownloadMessage("");
  }

  function applyPreset(presetId: string) {
    const preset = PORTFOLIO_SCREEN_PRESETS.find(
      (item) => item.id === presetId,
    );
    if (!preset) return;
    setRules(preset.rules.map((rule) => ({ ...rule })));
    setSortBy("name");
    setDirection("asc");
    setRulesOpen(false);
    setDownloadMessage("");
  }

  function reset() {
    setRules(PORTFOLIO_SCREEN_PRESETS[0].rules.map((rule) => ({ ...rule })));
    setLens("");
    setMatchingPeriodOnly(true);
    setIndustry("");
    setSector("");
    setSortBy("name");
    setDirection("asc");
    setCompanyQuery("");
    setView("overview");
    setRulesOpen(false);
    setDisclosuresOpen(false);
    setDownloadMessage("");
  }

  function addRule() {
    const used = new Set(rules.map((rule) => rule.metricId));
    const metric = availableMetrics.find((item: any) => !used.has(item.id));
    if (!metric || rules.length >= 4) return;
    setRules((current) => [
      ...current,
      { metricId: metric.id, min: "", max: "" },
    ]);
    setRulesOpen(true);
    setSortBy("name");
    setDownloadMessage("");
  }

  function sort(column: string) {
    if (effectiveSort === column) {
      setDirection((current) => (current === "asc" ? "desc" : "asc"));
    } else {
      setSortBy(column);
      setDirection(column === "name" ? "asc" : "desc");
    }
  }

  function sortState(column: string) {
    if (effectiveSort !== column) return "none" as const;
    return direction === "asc"
      ? ("ascending" as const)
      : ("descending" as const);
  }

  function selectView(next: string) {
    setView(next);
    setSortBy("name");
    setDirection("asc");
  }

  function moveTab(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key))
      return;
    event.preventDefault();
    const nextIndex =
      event.key === "Home"
        ? 0
        : event.key === "End"
          ? availableViews.length - 1
          : (index +
              (event.key === "ArrowRight" ? 1 : -1) +
              availableViews.length) %
            availableViews.length;
    selectView(availableViews[nextIndex].id);
    const tabs = event.currentTarget.parentElement?.querySelectorAll<HTMLElement>(
      '[role="tab"]',
    );
    tabs?.[nextIndex]?.focus();
  }

  function download() {
    try {
      downloadText(
        "portfolio-screen-results.csv",
        portfolioScreenCsv(result),
        "text/csv;charset=utf-8",
      );
      setDownloadMessage(
        `CSV prepared with all ${result.matches.length} analytical matches, exact periods and SEC sources.`,
      );
    } catch {
      setDownloadMessage(
        "The CSV could not be prepared. Check the rules and try again.",
      );
    }
  }

  const unusedMetricCount = availableMetrics.filter(
    (metric: any) => !ruleMetricIds.has(metric.id),
  ).length;
  const activeFilterCount =
    rules.length +
    Number(Boolean(sector)) +
    Number(Boolean(industry)) +
    Number(Boolean(lens));

  return (
    <section className={styles.screener} aria-labelledby={`${id}-title`}>
      <header className={styles.compactHeader}>
        <div>
          <span className={styles.eyebrow}>Company screener</span>
          <h3 id={`${id}-title`}>All portfolio companies</h3>
          <p>
            Filter captured SEC fundamentals and open the filing behind every
            result.
          </p>
        </div>
        <div className={styles.headerActions}>
          <span className={styles.captureBadge}>
            {report.metrics.length} SEC-backed measures
          </span>
          <button type="button" className={styles.quietAction} onClick={reset}>
            <RotateCcw size={15} aria-hidden="true" /> Reset
          </button>
          {onDisclosure ? (
            <button
              type="button"
              className={styles.quietAction}
              aria-expanded={disclosuresOpen}
              aria-controls={`${id}-disclosures`}
              onClick={() => setDisclosuresOpen((current) => !current)}
            >
              <FileSearch size={16} aria-hidden="true" /> Disclosures
            </button>
          ) : null}
          <button
            type="button"
            className={styles.primaryAction}
            disabled={!result.valid || !result.matches.length}
            onClick={download}
          >
            <Download size={16} aria-hidden="true" /> Download CSV
          </button>
        </div>
      </header>

      {disclosuresOpen && onDisclosure ? (
        <div className={styles.disclosureBar} id={`${id}-disclosures`}>
          <label htmlFor={`${id}-disclosure-query`}>
            Search disclosures across all analytical matches
          </label>
          <div>
            <Search size={16} aria-hidden="true" />
            <input
              id={`${id}-disclosure-query`}
              value={disclosureQuery}
              maxLength={200}
              onChange={(event) => setDisclosureQuery(event.target.value)}
              placeholder="Topic or phrase"
            />
          </div>
          <button
            type="button"
            disabled={!disclosureQuery.trim() || !result.matches.length}
            onClick={() =>
              onDisclosure(
                disclosureQuery.trim(),
                result.matches.map((row: any) => row.cik),
              )
            }
          >
            Search {result.matches.length} companies
          </button>
        </div>
      ) : null}

      <div className={styles.filterShell}>
        <div className={styles.filterRail} aria-label="Screener filters">
          <label className={`${styles.selectChip} ${styles.quickScreen}`}>
            <span>Quick screens</span>
            <select
              value=""
              aria-label="Apply a quick research screen"
              onChange={(event) => applyPreset(event.target.value)}
            >
              <option value="">Choose…</option>
              {presets.map((preset) => (
                <option key={preset.id} value={preset.id}>
                  {preset.label}
                </option>
              ))}
            </select>
          </label>

          {rules.map((rule, index) => {
            const metric = metricById.get(rule.metricId);
            const unavailable = !availableMetricIds.has(rule.metricId);
            return (
              <div
                className={`${styles.ruleChip} ${
                  unavailable ? styles.ruleChipUnavailable : ""
                }`}
                key={`${rule.metricId}-${index}`}
              >
                <button
                  type="button"
                  aria-haspopup="dialog"
                  aria-expanded={rulesOpen}
                  onClick={() => setRulesOpen(true)}
                  title={
                    unavailable
                      ? "This measure has no usable evidence in the current scope."
                      : "Edit this inclusive financial rule"
                  }
                >
                  {ruleLabel(rule, metric)}
                </button>
                <button
                  type="button"
                  className={styles.removeChip}
                  disabled={rules.length === 1}
                  aria-label={`Remove ${metric?.label || `rule ${index + 1}`}`}
                  onClick={() => {
                    setRules((current) =>
                      current.filter((_, itemIndex) => itemIndex !== index),
                    );
                    setSortBy("name");
                    setDownloadMessage("");
                  }}
                >
                  <X size={13} aria-hidden="true" />
                </button>
              </div>
            );
          })}

          <button
            type="button"
            className={styles.addFilter}
            disabled={rules.length >= 4 || !unusedMetricCount}
            onClick={addRule}
          >
            <Plus size={14} aria-hidden="true" /> Financial rule
          </button>

          <label
            className={`${styles.selectChip} ${sector ? styles.activeChip : ""}`}
          >
            <span>Sector</span>
            <select
              value={sector}
              aria-label="Filter by sector"
              onChange={(event) => {
                setSector(event.target.value);
                setSortBy("name");
                setDownloadMessage("");
              }}
            >
              <option value="">All sectors</option>
              {result.sectors.map((item: string) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </label>

          <label
            className={`${styles.selectChip} ${industry ? styles.activeChip : ""}`}
          >
            <span>SEC industry</span>
            <select
              value={industry}
              aria-label="Filter by SEC industry"
              onChange={(event) => {
                setIndustry(event.target.value);
                setSortBy("name");
                setDownloadMessage("");
              }}
            >
              <option value="">All SEC industries</option>
              {result.industries.map((item: string) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </label>

          <label
            className={`${styles.selectChip} ${lens ? styles.activeChip : ""}`}
          >
            <span>Financial set</span>
            <select
              value={lens}
              aria-label="Filter by compatible financial set"
              onChange={(event) => {
                setLens(event.target.value);
                setSortBy("name");
                setDownloadMessage("");
              }}
            >
              <option value="">All financial sets</option>
              {[...lensCounts.entries()]
                .sort(([a], [b]) =>
                  (LENS_LABELS[a] || a).localeCompare(LENS_LABELS[b] || b),
                )
                .map(([item, count]) => (
                  <option key={item} value={item}>
                    {LENS_LABELS[item] || item} ({count})
                  </option>
                ))}
            </select>
          </label>

          {report.fullPeriodEvidence ? (
            <button
              type="button"
              role="switch"
              aria-checked={matchingPeriodOnly}
              className={`${styles.periodChip} ${
                matchingPeriodOnly ? styles.activeChip : ""
              }`}
              onClick={() => {
                setMatchingPeriodOnly((current) => !current);
                setSortBy("name");
              }}
              title="Require every selected rule to use the same exact full reporting window within each company"
            >
              <span aria-hidden="true">{matchingPeriodOnly ? "✓" : "○"}</span>
              Same full period
            </button>
          ) : null}

          <span className={styles.logicChip}>
            Match all · {activeFilterCount} active
          </span>
        </div>

        {rulesOpen ? (
          <section
            className={styles.ruleEditor}
            role="dialog"
            aria-modal="false"
            aria-labelledby={`${id}-rule-editor-title`}
          >
            <header>
              <div>
                <strong id={`${id}-rule-editor-title`}>Financial rules</strong>
                <span>
                  Match all rules · inclusive bounds · {rules.length}/4 used
                </span>
              </div>
              <button
                type="button"
                className={styles.iconButton}
                aria-label="Close financial rule editor"
                onClick={() => setRulesOpen(false)}
              >
                <X size={17} aria-hidden="true" />
              </button>
            </header>
            <div className={styles.ruleGrid}>
              {rules.map((rule, index) => {
                const metric = metricById.get(rule.metricId) as any;
                const unavailable = !availableMetricIds.has(rule.metricId);
                const duplicateIds = new Set(
                  rules
                    .filter((_, itemIndex) => itemIndex !== index)
                    .map((item) => item.metricId),
                );
                const ruleError = result.errors.find((error: string) =>
                  error.startsWith(`Rule ${index + 1}:`),
                );
                return (
                  <fieldset className={styles.rule} key={index}>
                    <legend>
                      Rule {index + 1}
                      {index ? " · AND" : ""}
                    </legend>
                    <label className={styles.metricPicker}>
                      Measure
                      <select
                        value={rule.metricId}
                        aria-invalid={Boolean(unavailable)}
                        onChange={(event) =>
                          changeRule(index, {
                            metricId: event.target.value,
                            min: "",
                            max: "",
                          })
                        }
                      >
                        {unavailable && metric ? (
                          <optgroup label="Unavailable in this scope">
                            <option value={metric.id}>
                              {metric.label} ({metric.unit})
                            </option>
                          </optgroup>
                        ) : null}
                        {metricGroups.map(([group, metrics]) => (
                          <optgroup key={group} label={group}>
                            {metrics.map((item: any) => (
                              <option
                                key={item.id}
                                value={item.id}
                                disabled={duplicateIds.has(item.id)}
                              >
                                {item.label} ({item.unit})
                              </option>
                            ))}
                          </optgroup>
                        ))}
                      </select>
                    </label>
                    <label>
                      Minimum ({metric?.unit || "value"})
                      <input
                        type="text"
                        inputMode="decimal"
                        value={rule.min}
                        placeholder="No minimum"
                        aria-describedby={`${id}-bounds`}
                        aria-invalid={Boolean(ruleError)}
                        onChange={(event) =>
                          changeRule(index, { min: event.target.value })
                        }
                      />
                    </label>
                    <label>
                      Maximum ({metric?.unit || "value"})
                      <input
                        type="text"
                        inputMode="decimal"
                        value={rule.max}
                        placeholder="No maximum"
                        aria-describedby={`${id}-bounds`}
                        aria-invalid={Boolean(ruleError)}
                        onChange={(event) =>
                          changeRule(index, { max: event.target.value })
                        }
                      />
                    </label>
                    <button
                      type="button"
                      className={styles.removeRule}
                      disabled={rules.length === 1}
                      onClick={() => {
                        setRules((current) =>
                          current.filter((_, itemIndex) => itemIndex !== index),
                        );
                        setSortBy("name");
                      }}
                    >
                      Remove
                    </button>
                    {unavailable ? (
                      <p className={styles.ruleWarning}>
                        No usable evidence for this measure in the current
                        scope. Change the measure or broaden the scope.
                      </p>
                    ) : ruleError ? (
                      <p className={styles.ruleWarning}>{ruleError}</p>
                    ) : null}
                  </fieldset>
                );
              })}
            </div>
            <footer>
              <button
                type="button"
                disabled={rules.length >= 4 || !unusedMetricCount}
                onClick={addRule}
              >
                <Plus size={14} aria-hidden="true" /> Add rule
              </button>
              <p id={`${id}-bounds`}>
                Use at least one bound. Enter 10 for 10%, or 1 for a 1× ratio.
                Minimums and maximums are included. Missing values never pass.
              </p>
            </footer>
          </section>
        ) : null}

        <div
          className={styles.categoryTabs}
          role="tablist"
          aria-label="Financial table views"
        >
          {availableViews.map((item, index) => {
            const selected = activeView.id === item.id;
            return (
              <button
                type="button"
                role="tab"
                key={item.id}
                id={`${id}-tab-${item.id}`}
                aria-selected={selected}
                aria-controls={`${id}-results`}
                tabIndex={selected ? 0 : -1}
                onClick={() => selectView(item.id)}
                onKeyDown={(event) => moveTab(event, index)}
              >
                {item.label}
              </button>
            );
          })}
        </div>
      </div>

      {unavailableRules.length ? (
        <button
          type="button"
          className={styles.scopeWarning}
          onClick={() => setRulesOpen(true)}
        >
          <SlidersHorizontal size={15} aria-hidden="true" />
          {unavailableRules.length} active {unavailableRules.length === 1 ? "rule has" : "rules have"} no usable evidence in this scope. Review rules.
        </button>
      ) : null}

      {!result.valid ? (
        <div className={styles.error} role="alert">
          <strong>Complete the financial rules to screen companies.</strong>
          <ul>
            {result.errors.map((error: string) => (
              <li key={error}>{error}</li>
            ))}
          </ul>
        </div>
      ) : (
        <>
          <div className={styles.resultBar} aria-live="polite" aria-atomic="true">
            <strong>{result.matchCount} matches</strong>
            {report.weighted ? (
              <span className={styles.weightResult}>
                {percent(result.knownMatchedWeightPct)} known weight
              </span>
            ) : null}
            <span title="Companies with every required value and compatible full periods">
              {result.measuredCount} fully measured
            </span>
            <span title="Eligible companies missing at least one required value">
              {result.missingCount} missing
            </span>
            <span title="Companies for which at least one selected measure does not apply">
              {result.notApplicableCount} N/A
            </span>
            <span title="Fully measured companies outside at least one inclusive bound">
              {result.outside.length} outside bounds
            </span>
            {result.mismatched.length ? (
              <span title="Selected measures do not share the same exact full period within the company">
                {result.mismatched.length} period mismatch
              </span>
            ) : null}
          </div>

          <div className={styles.resultsToolbar}>
            <div className={styles.resultTitle}>
              <strong>{activeView.label}</strong>
              <span>{activeView.description}</span>
            </div>
            <label className={styles.companySearch}>
              <Search size={15} aria-hidden="true" />
              <span className={styles.srOnly}>Search matching companies</span>
              <input
                value={companyQuery}
                onChange={(event) => setCompanyQuery(event.target.value)}
                placeholder="Search matches"
              />
              {companyQuery ? (
                <button
                  type="button"
                  aria-label="Clear company search"
                  onClick={() => setCompanyQuery("")}
                >
                  <X size={14} aria-hidden="true" />
                </button>
              ) : null}
            </label>
            <span className={styles.showingCount}>
              Showing {visibleMatches.length} of {result.matches.length}
            </span>
          </div>

          <div
            id={`${id}-results`}
            role="tabpanel"
            aria-labelledby={`${id}-tab-${activeView.id}`}
          >
            {visibleMatches.length ? (
              <CompanyResearchTable
                label={`${activeView.label}: matching company financial measures`}
                className={styles.tableShell}
                resetKey={`${activeView.id}:${sector}:${industry}:${lens}`}
              >
                <table className={styles.resultsTable}>
                  <caption className={styles.srOnly}>
                    Matching portfolio companies. Financial values are reported
                    to the SEC or calculated from the captured filing evidence.
                  </caption>
                  <thead>
                    <tr>
                      <th scope="col" aria-sort={sortState("name")}>
                        <button
                          type="button"
                          className={styles.sortButton}
                          onClick={() => sort("name")}
                        >
                          Company
                          {effectiveSort === "name" ? (
                            direction === "asc" ? (
                              <ArrowUp size={13} aria-hidden="true" />
                            ) : (
                              <ArrowDown size={13} aria-hidden="true" />
                            )
                          ) : null}
                        </button>
                      </th>
                      {displayMetrics.map((metric) => (
                        <th
                          scope="col"
                          key={metric.id}
                          aria-sort={sortState(metric.id)}
                          className={
                            ruleMetricIds.has(metric.id)
                              ? styles.ruleColumn
                              : undefined
                          }
                        >
                          <button
                            type="button"
                            className={styles.sortButton}
                            onClick={() => sort(metric.id)}
                          >
                            <span>{metric.label}</span>
                            <small>{metric.unit}</small>
                            {effectiveSort === metric.id ? (
                              direction === "asc" ? (
                                <ArrowUp size={13} aria-hidden="true" />
                              ) : (
                                <ArrowDown size={13} aria-hidden="true" />
                              )
                            ) : null}
                          </button>
                        </th>
                      ))}
                      {report.weighted ? (
                        <th scope="col" aria-sort={sortState("weight")}>
                          <button
                            type="button"
                            className={styles.sortButton}
                            onClick={() => sort("weight")}
                          >
                            Known weight
                            {effectiveSort === "weight" ? (
                              direction === "asc" ? (
                                <ArrowUp size={13} aria-hidden="true" />
                              ) : (
                                <ArrowDown size={13} aria-hidden="true" />
                              )
                            ) : null}
                          </button>
                        </th>
                      ) : null}
                      <th scope="col">Sector</th>
                      <th scope="col">Financial set</th>
                    </tr>
                  </thead>
                  <tbody>
                    {visibleMatches.map((row: any) => (
                      <tr key={row.cik}>
                        <th scope="row">
                          <button
                            type="button"
                            className={styles.company}
                            disabled={!row.rowId}
                            onClick={() => onInspectCompany(row.rowId)}
                          >
                            <span className={styles.ticker}>
                              {row.tickers.join(" / ") || "CIK"}
                            </span>
                            <span className={styles.companyName}>{row.name}</span>
                          </button>
                          <small className={styles.companyMeta}>
                            {row.industry || "SEC industry unavailable"}
                          </small>
                        </th>
                        {displayMetrics.map((metric) => {
                          const cell = [
                            ...(row.cells || []),
                            ...(row.displayCells || []),
                          ].find((item: any) => item.metricId === metric.id);
                          const status = cell?.status || "missing";
                          return (
                            <td
                              key={metric.id}
                              className={`${styles.metricCell} ${
                                ruleMetricIds.has(metric.id)
                                  ? styles.ruleColumn
                                  : ""
                              }`}
                            >
                              {status === "available" ? (
                                <>
                                  <strong>{formatValue(cell.value, cell.unit)}</strong>
                                  <span title={cell.periodKey?.replaceAll("|", " · ") || cell.periodEnd}>
                                    {periodLabel(cell, metric.category)}
                                  </span>
                                  {cell.sourceUrl ? (
                                    <a
                                      href={cell.sourceUrl}
                                      target="_blank"
                                      rel="noopener noreferrer"
                                      aria-label={`${row.name}: ${cell.label} SEC filing source`}
                                      title="Open SEC filing evidence"
                                    >
                                      SEC <ExternalLink size={11} aria-hidden="true" />
                                    </a>
                                  ) : (
                                    <small>No direct link</small>
                                  )}
                                </>
                              ) : (
                                <>
                                  <strong className={styles.unavailableValue}>
                                    {status === "not-applicable" ? "N/A" : "Missing"}
                                  </strong>
                                  <span>
                                    {status === "not-applicable"
                                      ? "Not applicable to this financial set"
                                      : "No usable captured value"}
                                  </span>
                                </>
                              )}
                            </td>
                          );
                        })}
                        {report.weighted ? (
                          <td className={styles.weightCell}>
                            <strong>{percent(row.weightPct)}</strong>
                            {!row.weightComplete ? (
                              <span>Known subtotal</span>
                            ) : (
                              <span>Original weight</span>
                            )}
                          </td>
                        ) : null}
                        <td className={styles.classificationCell}>
                          <strong>
                            {row.sector || PORTFOLIO_SECTOR_UNCOVERED}
                          </strong>
                          <span>Portfolio classification</span>
                        </td>
                        <td className={styles.classificationCell}>
                          <strong>{LENS_LABELS[row.lens] || row.lens}</strong>
                          <span>Compatible accounting measures</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CompanyResearchTable>
            ) : (
              <div className={styles.emptyState}>
                <Search size={20} aria-hidden="true" />
                <strong>
                  {normalizedQuery
                    ? `No matching company contains “${companyQuery.trim()}”.`
                    : "No measured company satisfies every active rule."}
                </strong>
                <button
                  type="button"
                  onClick={() =>
                    normalizedQuery
                      ? setCompanyQuery("")
                      : setRulesOpen(true)
                  }
                >
                  {normalizedQuery ? "Clear search" : "Review rules"}
                </button>
              </div>
            )}
          </div>

          <details className={styles.exclusions}>
            <summary>
              Screening audit · {result.outside.length + result.missing.length + result.notApplicable.length + result.mismatched.length} excluded companies
            </summary>
            <p>
              Missing values never pass. Not-applicable measures and exact-period
              mismatches remain separate from companies outside the selected
              inclusive bounds.
            </p>
            <div className={styles.auditColumns}>
              {[
                ["Outside bounds", result.outside],
                ["Missing a value", result.missing],
                ["Not applicable", result.notApplicable],
                ["Period mismatch", result.mismatched],
              ].map(([label, rows]: any) =>
                rows.length ? (
                  <section key={label}>
                    <h4>{label} · {rows.length}</h4>
                    <ul>
                      {rows.map((row: any) => (
                        <li key={row.cik}>
                          <button
                            type="button"
                            disabled={!row.rowId}
                            onClick={() => onInspectCompany(row.rowId)}
                          >
                            {row.tickers.join(" / ") || row.name}
                          </button>
                          <span>
                            {label === "Outside bounds"
                              ? row.failures.join(" · ")
                              : label}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </section>
                ) : null,
              )}
            </div>
          </details>
        </>
      )}

      {downloadMessage ? (
        <p className={styles.statusMessage} role="status">
          {downloadMessage}
        </p>
      ) : null}
      <details className={styles.methodology}>
        <summary>About this screen and its denominators</summary>
        <p>
          Rules are joined with AND and both bounds are inclusive. Each row is
          one canonical SEC issuer; share classes are combined. Original
          portfolio weights are retained and never normalized inside the
          shortlist. Reporting windows may differ across companies.
        </p>
        <p>
          Sector comes from the portfolio’s fund classification; SEC industry
          comes from SIC. This captured research does not include live prices,
          market capitalizations, analyst ratings or technical indicators.
          {result.unresolvedCount
            ? ` ${result.unresolvedCount} unresolved positions remain outside the screen.`
            : ""}
        </p>
      </details>
    </section>
  );
}
